### ISSUE TITLE
Telemetry remnants still there

### ISSUE THREAD

**Issue by OdinVex** [Murmele/Gittyup#108]
A quick Issues search revealed the mostly-complete removal of telemetry-related stuff, but the Flatpak version (“1.0.0, Mon, Jan 3, 2022”) has a disabled (but ticked) checkbox for Usage Reporting with a Privacy Policy.

**Comment by Murmele** [comment]
Yes in the flatpak version on flathub I just disabled and commented out everything but let the checkbox in. In the development cersion everything was removed cleanly. Check out the development version in the releases

**Comment by OdinVex** [comment]
> Yes in the flatpak version on flathub I just disabled and commented out everything but let the checkbox in. In the development cersion everything was removed cleanly. Check out the development version in the releases

Thanks for following up on this inquiry, I appreciate it. Nerves at ease. :)
