### ISSUE TITLE
Segmentation fault when using spacebar to select files in Unstaged Files

### ISSUE THREAD

**Issue by slackerbob** [Murmele/Gittyup#109]
Frequently, while selecting files by pressing the spacebar in the Unstaged Files window, the program crashes with:

`Segmentation fault (core dumped)`

More messages:

```
Diff Header:
"@@ -1,7 +1,7 @@\n"
Staged Header:
"@@ -1,7 +1,7 @@\n"
Patch lines: 8
0 )  "Origin:  ; OldLine: 1; NewLine: 1"
1 )  "Origin:  ; OldLine: 2; NewLine: 2"
2 )  "Origin:  ; OldLine: 3; NewLine: 3"
3 )  "Origin: -; OldLine: 4; NewLine: "
4 )  "Origin: +; OldLine: ; NewLine: 4"
5 )  "Origin:  ; OldLine: 5; NewLine: 5"
6 )  "Origin:  ; OldLine: 6; NewLine: 6"
7 )  "Origin:  ; OldLine: 7; NewLine: 7"
Staged linesStaged: 1
Staged patch No.  0
0 )  "Origin:  ; OldLine: 1; NewLine: 1"
1 )  "Origin:  ; OldLine: 2; NewLine: 2"
2 )  "Origin:  ; OldLine: 3; NewLine: 3"
3 )  "Origin: -; OldLine: 4; NewLine: "
4 )  "Origin: +; OldLine: ; NewLine: 4"
5 )  "Origin:  ; OldLine: 5; NewLine: 5"
6 )  "Origin:  ; OldLine: 6; NewLine: 6"
7 )  "Origin:  ; OldLine: 7; NewLine: 7"
Name:  "Staged"  Row:  0 :  "Services" ; Count:  1
Name:  "Staged" , countCollapsed(): 1
Name:  "Staged" Current Collapsed:  1 ; New Collapsed:  1
Segmentation fault (core dumped)
```

Steps to reproduce:

1. Open program
2. Open a repo with sidebar or "Open Repository" with one or more unstaged files.
3. With the "Unstaged Files" window focused, press spacebar to select a file.
4. Roughly 20% of the time, this will result in the program closing with a segmentation fault.

System info:
Arch Linux x64
5.16.11-arch1-1
gcc version: 11.2.0-3
Compiled from source, via the [AUR](https://aur.archlinux.org/packages/gittyup-git)
On current commit as of March 4th

If there's any additional info/tests you need, I'm happy to help.

**Comment by stefanknotzer** [comment]
Acknowledged: `Q_ASSERT(isStageEnabled());` in DetailView.cpp

**Comment by Murmele** [comment]
@slackerbob is it possible if you create an example repository (just create a new one and create a few files in there and try to reproduce it) on which only step 3 must be done to reproduce it, because it depends on the content of the repository

**Comment by Murmele** [comment]
[Test.zip](https://github.com/Murmele/Gittyup/files/8512920/Test.zip)

1) Select "New Folder/New Folder2/Test123.txt"
2) Press space

**Comment by Murmele** [comment]
I tried this again out and I get a segfault in the qt library it self and not in DetailView.cpp. @slackerbob can you try to reproduce?

**Comment by Murmele** [comment]
@slackerbob is the issue still reproducable? We have a merge request pending so we prioritze it if still an issue

**Comment by slackerbob** [comment]
I can no longer reproduce this issue.

Thank you for the fix!

And my apologies for taking so long to respond.

**Comment by Murmele** [comment]
Hmm strange. I am still able to reproduce it
