### ISSUE TITLE
Stable binary release?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [Murmele/Gittyup#123]
hi, where can i get the stable binary release? the readme says the prerelease is available, but what's the stance on stable releases?

thanks (:

**Comment by Murmele** [comment]
Hi,
for linux you can use the flatpak package: https://flathub.org/apps/details/com.github.Murmele.Gittyup
Currently for the others there does not exist a stable yet.
You can try the prerelease

**Comment by yashpalgoyal1304** [comment]
ohkay, thanks for replying (:
