### ISSUE TITLE
[Bug] Dark theme does not theme menu (on Linux Mint?)

### ISSUE THREAD

**Issue by OdinVex** [Murmele/Gittyup#126]
I've attached a screenshot to show the issue. The menu bar isn't themed at all, despise my selecting `Dark`. For now, I've decided to use the `System` theme, and it works well for me. See below for screenshot. (I dislike embedding without being able to use a spoiler wrapped around.)

[Broken Dark Theme](https://user-images.githubusercontent.com/44311901/161399022-c6552ee5-7ec4-4fb5-b081-46a5206ef730.png)

**Comment by Murmele** [comment]
@OdinVex can you try the latest version?

**Comment by OdinVex** [comment]
@Murmele, com.github.Murmele.Gittyup v1.1.2 stable, still occurs. Using Mint 21 at the moment.

**Comment by OdinVex** [comment]
Fixed by #260, closing.

**Comment by rebeccasodergren** [comment]
@OdinVex Inga problem! :smile_cat:
