### ISSUE TITLE
SSH connectivity on Windows 10

### ISSUE THREAD

**Issue by wrmbaron** [Murmele/Gittyup#134]
There has been a problem with SSH connectivity on Windows 10 since version 1903. Libssh2-1.10.0 solves that problem.

The current version of Gittyup still references version 1.9.0. Could you please update the references submodule version for libssh2 to libssh2-1.10.0?

**Comment by Murmele** [comment]
We have to update all dependencies. I hope I come to it next days

**Comment by Murmele** [comment]
@wrmbaron 
can you try the artifacts of this version as soon as it is finished?
https://github.com/Murmele/Gittyup/pull/137
https://github.com/Murmele/Gittyup/runs/6141279292?check_suite_focus=true

**Comment by Murmele** [comment]
You can see the artifacts in the summary (bottom of the page):
https://github.com/Murmele/Gittyup/actions/runs/2212892212

We will create next days a release after this the MR will be merged then you get a latest release of the version.

**Comment by Murmele** [comment]
closed by #137
