### ISSUE TITLE
Remove one trigger of github actions, because currently two triggers are created

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#151]
Currently when creating a pullrequest two triggers are created. Probably this is because in the build.yml

on:
  push:
  pull_request

is included. This uses a lot of computational power. @exactly-one-kas  do you think we can do the action only for pushes on master or do you need it for something else?

on:
  push:
    "master"
  pull_request

**Comment by exactly-one-kas** [comment]
I don't need a build on every push. If necessary, I can just manually start the pipeline with the `workflow_dispatch` trigger.
