### ISSUE TITLE
"TLS initialization failed" while adding account 

### ISSUE THREAD

**Issue by MMariusch** [Murmele/Gittyup#177]
Hi
when I try to add an account to the client I get this message. After that the client shuts down.
I'm working on Windows 10 version 19044.1706.

![Untitled](https://user-images.githubusercontent.com/49458986/169905899-a337cd3d-2748-4a5b-89f4-d3b90d937451.png)

**Comment by exactly-one-kas** [comment]
I can't reproduce the TLS error (Windows 10 Pro 64-Bit 19044.1645), but I'll try again after the next update.
Are you using https://gitlab.com?

I can however reproduce the crash after a failed login attempt.

**Comment by Anixias** [comment]
I can confirm this issue also occurs for GitHub accounts.

**Comment by exactly-one-kas** [comment]
@MMariusch @Anixias Can you try out the following build and report back the extended error message?

https://github.com/exactly-one-kas/Gittyup/actions/runs/2519652721#artifacts

**Comment by micgao** [comment]
I'm getting the same error/crash when trying to login using PAT. Using the link provided above fixes the crash, but am still unable to login. 

Windows 11 latest Insiders Beta

**Comment by micgao** [comment]
> @micgao Did the error message say anything other than `TLS initialization failed`?

No, exact same error message as OP. Crashes when I click OK on the error message. This happens with PAT or just regular password authentication (I tried with both Github and Gitlab)

**Comment by pimise** [comment]
> > @micgao Did the error message say anything other than `TLS initialization failed`?
> 
> No, exact same error message as OP. Crashes when I click OK on the error message. This happens with PAT or just regular password authentication (I tried with both Github and Gitlab)

Exactly the same here. On a fresh install of WSL on a new Windows Session.
