### ISSUE TITLE
GittyUp wont start

### ISSUE THREAD

**Issue by Yaksinikos** [Murmele/Gittyup#180]
System:
Manjaro Linux, Kernel 5.17.9-1
Language: DE
DE: MATE Desktop

Gittyup version: 1.1.0-1
Installed from AUR: https://aur.archlinux.org/packages/gittyup

GUI does not even open, using the menu.
Starting using the terminal-console returns a error:

```
`[user@user Desktop]$ gittyup
Theme dir:  QDir( "/var/tmp/pamac-build-rt5/gittyup/src/gittyup/conf" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/var/tmp/pamac-build-rt5/gittyup/src/gittyup/conf" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /var/tmp/pamac-build-rt5/gittyup/src/gittyup/conf/System.lua: Datei oder Verzeichnis nicht gefunden / File or Location not found)
Canceled (Speicherabzug geschrieben / Memory Error)`
```

**Comment by Murmele** [comment]
Related to #167
Currently the AUR package is not officially supported by us. We have currently only the flatpak package: https://flathub.org/apps/details/com.github.Murmele.Gittyup
