### ISSUE TITLE
Ubuntu 22.04: Misaligned menu

### ISSUE THREAD

**Issue by Pietro395** [Murmele/Gittyup#188]
Installed via Flatpak on Ubuntu 22.04, the menu is misaligned

![immagine](https://user-images.githubusercontent.com/50447537/172649785-c5da89ee-be3e-42bb-83f5-9acece7566b3.png)

![immagine](https://user-images.githubusercontent.com/50447537/172649896-74cf04da-fb21-43cc-850e-69751fe27e97.png)

**Comment by Murmele** [comment]
I had this problem too a few versions of flatpak ago. Which version of flatpak are you using?

**Comment by skar395** [comment]
> I had this problem too a few versions of flatpak ago. Which version of flatpak are you using?

Flatpak 1.12.7
The official ppa doesn't support ubuntu 22.04 yet
