### ISSUE TITLE
Launch from terminal. Quiet script.

### ISSUE THREAD

**Issue by barreiroleo** [Murmele/Gittyup#193]
Hello there!
I did this for running the flatpak version easily from console. Disown the process and silence the output pushing it to /dev/null.
Just save the script somewhere in your path, give execution permissions (chmod +x), and run `gittyup` from your terminal, then be happy.
I hope it helps someone. 

```bash
#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}") # Relative

function run_disown() {
    "$@" & disown
}

function run_disown_silence(){
    run_disown "$@" 1>/dev/null 2>/dev/null
}

run_disown_silence flatpak run com.github.Murmele.Gittyup
```

**Comment by Murmele** [comment]
@barreiroleo thanks for posting. The output on the console we use normaly for debugging purpose. Are you opening the gui always from terminal to not have to click in the menu?
Should we implement something in Gittyup or is it just as information for others?

**Comment by barreiroleo** [comment]
I spend a lot of time in the terminal, vim, compiling, testing, git, etc. I use the GUI in specific situations, so launching it from the terminal becomes very comfortable and fast.
I doubt that flatpak will let you add something to the path, so this is a tip for someone who lives in the console.
Maybe you want to pin the issue, put it on the wiki or add it to the readme, I don't know.

Great job, its one of the best clients i have tried.

**Comment by Murmele** [comment]
Yes great idea, I will add it to the readme. 

Thanks this is a pleasure to here. I wozld also thank to @exactly-one-kas and @stefanknotzer for your help. I think we have now a really good setup to go on :)

**Comment by barreiroleo** [comment]
If you want, I'll do a PR in a bit.

**Comment by barreiroleo** [comment]
If you want, I'll do a PR in a bit.

**Comment by Murmele** [comment]
I will close, because the PR can be merged from my side
