### ISSUE TITLE
Cannot update Gittyup - "Some windows failed to close"

### ISSUE THREAD

**Issue by franktopel** [Murmele/Gittyup#199]
I cannot update Gittyup. I'm on 
<img width="205" alt="image" src="https://user-images.githubusercontent.com/10668603/174470774-39fc3c85-12c4-49f4-88b4-25a85e0e5559.png">

and my Gittup version is Gittyup v1.1.0 - 8. Mai 2022 - 56168eb

<img width="740" alt="image" src="https://user-images.githubusercontent.com/10668603/174470795-6aad4fa4-c57b-480c-8b51-60638c76cf2b.png">

Steps I do:

1. 
<img width="137" alt="image" src="https://user-images.githubusercontent.com/10668603/174470715-25ae87ff-25ed-44ea-ad3e-e57a59bec0c8.png">

2. 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/10668603/174470730-f7dc1769-31e0-46c5-a954-9451bcb6f64e.png">

3. 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/10668603/174470733-9754141e-db52-4fe6-864b-32a6a5940ab9.png">

**Comment by franktopel** [comment]
The same occurs when I close the Gittyup window manually before clicking "Install and Restart":

<img width="528" alt="image" src="https://user-images.githubusercontent.com/10668603/174470833-a58a62ff-ee62-4800-a091-6fbf3dab8e57.png">

**Comment by Murmele** [comment]
I can confirm this issue also on windows. I think for now you have to download it manually

**Comment by Murmele** [comment]
![grafik](https://user-images.githubusercontent.com/10099533/176871302-d60160e8-e197-4f97-8435-7fdb3c6b3878.png)

**Comment by exactly-one-kas** [comment]
This should be fixed with version 1.2.0, but you'll have to manually download and install the update
