### ISSUE TITLE
dead link(s) on the web site

### ISSUE THREAD

**Issue by alexn-s** [Murmele/Gittyup#207]
**issue**
the link to download the win version on the website (`https://murmele.github.io/Gittyup/`) is:
`https://github.com/Murmele/Gittyup/releases/download/stable/Gittyup-win64-1.1.0.exe`

the link is not available. only the newer release:
`https://github.com/Murmele/Gittyup/releases/download/stable/Gittyup-win64-1.1.1.exe`
is available.

probably the links for the other platforms are also invalid (did not check)

---

**suggestion**
remove the version from the downloads on the website and just link to
`https://github.com/Murmele/Gittyup/releases`

that way you dont need to update your site every time

**Comment by Murmele** [comment]
Hi @alexn-s thanks. I pushed it to ghpages, so it will be deployed soon. Was just not updated, because no new release since those updates was created
