### ISSUE TITLE
Is there a way to hide the menu bar?

### ISSUE THREAD

**Issue by erickod** [Murmele/Gittyup#213]
I would like to know if there's a config or something to do to hide the menu bar. Someone knows something about it?

**Comment by Murmele** [comment]
I think currently there is no way to hide the menu bar

**Comment by Murmele** [comment]
@erickod @OverEngineer created a pullrequest for it to fix it. We will get it soon

**Comment by exactly-one-kas** [comment]
This feature will be available in the upcoming 1.2.0 release
