### ISSUE TITLE
Enhancement: support remote repositories located on filesystem

### ISSUE THREAD

**Issue by alex-ball** [Murmele/Gittyup#215]
_Use case:_
I have a network drive that holds a bare Git repo. On my machine, I mount that network drive and clone that repository. I do work on the machine and push changes to the remote on the network drive, so I (or perhaps a colleague) can then pull the changes onto a different machine that can also access the same network drive.

_Current behaviour:_
Running Gittyup v1.1.1 on Ubuntu via Flatpak, attempting to push to or fetch from a filesystem remote fails with "unsupported URL protocol".

_Desired behaviour:_
With Git itself and the other clients I have tried, pushing to and fetching from a location on the filesystem works without difficulty.

I am really enjoying using Gittyup, so it would be great if I could use it with all my repositories.

**Comment by Murmele** [comment]
Hi alex,

can you try the proposal in #186?

possible dublicate of #186

**Comment by Murmele** [comment]
@alex-ball don't worry it is somehow an issue. But glad to here that you solved it.
