### ISSUE TITLE
AUR Build Error

### ISSUE THREAD

**Issue by hofq** [Murmele/Gittyup#217]
First i tried installing it using `paru -S gittyup` then `paru -S gittyup-git` and last with `git clone git clone https://aur.archlinux.org/gittyup.git` & `makepkg -si`
Always the Same error. 
Do you have an Idea how this could happen?

```
[***@*******-arch ~]$ gittyup
Theme dir:  QDir( "/home/***/packages/github/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/home/***/packages/github/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /home/***/packages/github/gittyup/src/build/Resources/System.lua: No such file or directory)
Aborted (core dumped)
[***@*****01-arch ~]$
```

**Comment by hofq** [comment]
OS: Arch 
Kernal: 5.18.12-zen1-1-zen
WM: Awesome

**Comment by TheArcaneBrony** [comment]
Is there any reason why it would be calling lua files from the build directory rather then an installed location in the first place?

**Comment by Murmele** [comment]
@elman22 got the Aur package to work.

**Comment by hofq** [comment]
I had no Build Error, but after the Build the Software wouldn't run and through the Same Error:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Theme dir:  QDir( "/home/jki/.cache/paru/clone/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Theme dir:  QDir( "/home/jki/.cache/paru/clone/gittyup/src/build/Resources" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
PANIC: unprotected error in call to Lua API (cannot open /home/jki/.cache/paru/clone/gittyup/src/build/Resources/System.lua: No such file or directory)
Aborted (core dumped)
`

**Comment by Murmele** [comment]
Ah ok I thought you got it completely run. Sorry then for disturbing

**Comment by hofq** [comment]
i use flatpak now :)

**Comment by Murmele** [comment]
> i use flatpak now :)

haha ^^.

**Comment by Murmele** [comment]
> 

He was able to get it running

**Comment by elman22** [comment]
When building directly from AUR, I got the same error as @hofq. But then I tried to edit PKGBUILD using patch by patlefort from https://aur.archlinux.org/packages/gittyup#comment-872036, changed version to 1.1.2 and it is working now.

**Comment by alerque** [comment]
Many of the issues AUR builds were running into have been fixed in `master`, but they haven't landed in a stable release yet. I'll update the stable AUR package when there is a new release. I've also contacated the `-git` package maintainer with an offer to help get it updated. In the mean time if you're hankering for a build you can try [this PKGBUILD]().

**Comment by Murmele** [comment]
@alerque this was the latest mr before the release mr. So it will not take that long anymore until the new release

**Comment by alerque** [comment]
Cool beans!

I don't think we're quite far enough along cleaning up the 3rd party dependency scene to move it to [community] this release cycle, but #314 sure brought it a lot closer. In any event even if [community] is one more release cycle off we should be able to get a pretty stable easy to compile AUR build going for *this* cycle (and of course I host prebuilt versions of all my AUR packages).
