### ISSUE TITLE
Automatic Fetch Option Ignored

### ISSUE THREAD

**Issue by leoplaw** [Murmele/Gittyup#230]
Configure Repository
Automatic Actions: Fetch  - disable / deselect

Fails, with application asking for authentication details every 10 minutes.

Deselecting ``Fetch every`` and or setting ``minutes`` to zero is ignored after submit ``OK``. Opening ``Configure Repository`` again and the option is still selected.

Editing the remote repository configuration files,
```
[autofetch]
	enable = false
	minutes = 0
```
also does not work.

Gittyup versions affected: 1.1.0, 1.1.1

Operating System: openSUSE Tumbleweed 20220205
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.4-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2670QM CPU @ 2.20GHz
Memory: 15.6 GiB of RAM
Graphics Processor: Quadro 3000M/PCIe/SSE2

**Comment by Murmele** [comment]
@leoplaw thanks fpr reporting. I will have a look into it

**Comment by leoplaw** [comment]
Further information:
I have two remotes configured for the local repo.
1. GitHub - uses GitHub authentication
2. private server which uses SSH for authentication

GittyUp is always asking every 10 minutes for the private server SSH authentication.
As outlined above, no matter what I do, I cannot seem to disable this.

**Comment by exactly-one-kas** [comment]
If you have saving credentials enabled, SSH passwords should be saved.
Is the package `git-credential-libsecret` or `git-credential-gnome-keyring` installed on your system?

**Comment by leoplaw** [comment]
The issue appears to be fixed in latest version:  v1.1.2 - 2022-08-12
