### ISSUE TITLE
"TLS initialization failed" while adding account

### ISSUE THREAD

**Issue by DatMayo** [Murmele/Gittyup#235]
Unfortunately I have the same issue as mentioned in #177. When I try to add my github account (2FA enabled, so PAT), I'm getting the same error.

Gittyup v1.1.1

/Edit: Even if I do "Check for updates" via Help menu, I'm getting the same error

**Comment by Murmele** [comment]
@exactly-one-kas prepared a new release with the fix in it. Will be v1.1.2

**Comment by exactly-one-kas** [comment]
v1.1.2 is now available: https://github.com/Murmele/Gittyup/releases/tag/stable

If this doesn't fix the problem, please just reopen this issue

**Comment by DatMayo** [comment]
@exactly-one-kas workes flawlessly :)
