### ISSUE TITLE
App will not upgrade from 1.1.1 to 1.1.2 on macOS - "Some windows failed to close"

### ISSUE THREAD

**Issue by liamjones** [Murmele/Gittyup#240]
I tried to install the latest update from inside the app. It downloads but when clicking 'Install and Restart' you just get a dialog stating:

> Unable to install update
> Some windows failed to close

I tried manually closing all windows before doing the update but you still get the same error message.

Running on macOS 12.5.

**Comment by liamjones** [comment]
Oh, and I should probably mention that the app was installed via homebrew in case that's relevant.

**Comment by exactly-one-kas** [comment]
This will be fixed with version 1.2.0
Since the installation via homebrew ist just a wrapper for the DMG file, this should work fine
