### ISSUE TITLE
"Staged Files" and "Unstaged Filed" were not updated after click "stage all" or "unstage all"

### ISSUE THREAD

**Issue by blueyee1122** [Murmele/Gittyup#244]
Hello,
when I click on "Stage All" button, the files on "Unstaged Files" view are still showing and "Staged Files" not showing. I had to click on "Refresh" button, everything is updated.

click "Stage All"
![image](https://user-images.githubusercontent.com/106735005/185025944-319b1b49-1520-4997-9f55-d19ee0295bf9.png)

**similar for Unstage All**
"Unstage all"
![image](https://user-images.githubusercontent.com/106735005/185026275-af84f6bd-8adf-46c4-b0cb-55079cd1c9d1.png)

I'm working on **Ubuntu 20.04.4 LTS - 64bit**
Gittyup version:  **v1.1.2**

**Comment by Murmele** [comment]
@blueyee1122 please add which version of Gittyup you are using

**Comment by blueyee1122** [comment]
> @blueyee1122 please add which version of Gittyup you are using

I'm using this version 
![image](https://user-images.githubusercontent.com/106735005/186073801-4d1a41c6-539b-451b-ae25-6741875e778e.png)

**Comment by mukha521** [comment]
The bug is still there.
Version 1.2.2

**Comment by jgodfrey** [comment]
I see this same issue on both Linux Mint 21.1 and Windows 11 using Gittyup v1.3.0 . Is this still a known problem?

**Comment by Murmele** [comment]
This is still a known problem.

**Comment by blueyee1122** [comment]
I have just reproduced, the files same hierarchy were OK. Like below
![image](https://user-images.githubusercontent.com/106735005/233890467-19539359-c85a-4c00-9712-0e90bbe86115.png)
BUT when these files putted inside any directory (b-directory/b.txt). They are not working properly
![image](https://user-images.githubusercontent.com/106735005/233890814-1e332c25-9732-4a0d-8b5b-de03fb00261f.png)
![image](https://user-images.githubusercontent.com/106735005/233890841-67270936-b5a0-4733-ae6b-74e4079e08b8.png)

**Comment by Murmele** [comment]
I will prioritize this problem next weekend!

**Comment by jgodfrey** [comment]
> I will prioritize this problem next weekend!

Nice - thank you!

**Comment by Murmele** [comment]
Can you try #534 ?

**Comment by jgodfrey** [comment]
I don't have access to a build environment ATM, but I'm happy to try a pre-built binary for LInux or Windows if you have one...

**Comment by Murmele** [comment]
@jgodfrey you don't need. There are build artifacts, so just download the bundle and install it

**Comment by Murmele** [comment]
@jgodfrey you downloaded the official 1.3.0 release, just the dev version of it. Check out my link and scroll down to the bottom
![image](https://user-images.githubusercontent.com/10099533/234359835-80dbaadd-4db5-4e49-b81f-68a367694b04.png)

**Comment by jgodfrey** [comment]
Hmmm... I'm not sure what I'm missing. I go to the link you provided above. Specifically:

https://github.com/Murmele/Gittyup/actions/runs/4789314963

I scroll down to the `Artifacts` section at the bottom and download the `Gittyup win64` artifact. The downloaded ZIP file contains `Gittyup-win64-1.3.0-dev.exe`. So, the DEV version of the 1.3.0 release (as you mentioned above). 

Where have I gone wrong?

**Comment by Murmele** [comment]
Hmm thats strange. This is fine what you did. I have to check tomorrow on windows

**Comment by Murmele** [comment]
> Hmmm... I'm not sure what I'm missing. I go to the link you provided above. Specifically:
> 
> https://github.com/Murmele/Gittyup/actions/runs/4789314963
> 
> I scroll down to the `Artifacts` section at the bottom and download the `Gittyup win64` artifact. The downloaded ZIP file contains `Gittyup-win64-1.3.0-dev.exe`. So, the DEV version of the 1.3.0 release (as you mentioned above).
> 
> Where have I gone wrong?

Sorry your version is correct and for me it is working fine

**Comment by jgodfrey** [comment]
Here's a GIF of what I'm seeing...

![gittyup_state_unstage_all](https://user-images.githubusercontent.com/1459347/234617486-b3783b2e-242d-4977-a3e1-be7483ac0677.gif)

**Comment by Murmele** [comment]
Ah you are using the list mode. I changed in treewidget mode. I have to check what I have to check there

**Comment by Murmele** [comment]
Great thanks. There it is more difficult to find out the parent folders without a hacking solution, so it will take a little bit until implemented

**Comment by jgodfrey** [comment]
@Murmele - While I haven't done any exhaustive testing of the latest build, for my simple example (GIF above), it works perfectly. I'll continue to play with it, but so far - it looks great! Thanks for the efforts here. :)
