### ISSUE TITLE
Cannot open Terminal on Macbook Apple Silicon

### ISSUE THREAD

**Issue by anzvanie** [Murmele/Gittyup#258]
When click to button `Open Terminal` I got the below message

>  No terminal executable was found. Please configure a terminal in the configuration.

I've tried running `osascript` command (found from source code) for get candidate in MacOS terminal but got an error message

```shell
% osascript -e "tell Finder to get application file id \"com.apple.Terminal\""

5:11: execution error: The variable Finder is not defined. (-2753)
```

My PC is Macbook Pro M1, and os version is 12.5

**Comment by exactly-one-kas** [comment]
We currently have no developer with macOS so we're flying blind

Does it work using `osascript -e "tell application Finder to get application file id \"com.apple.Terminal\""`?

**Comment by alex-ball** [comment]
No, that gives the same error.

However, this definitely does something (M1 chip, OS v12.5.1):

```bash
osascript -e "tell application \"Finder\" to get application file id \"com.apple.Terminal\""
```

This triggers a permission confirmation and returns

```
application file Terminal.app of folder Utilities of folder Applications of folder System of startup disk
```

**Comment by exactly-one-kas** [comment]
A permission confirmation doesn't sound ideal, I tried using the macOS API directly. Can you try the following build?

https://github.com/exactly-one-kas/Gittyup/actions/runs/2972101328
https://github.com/exactly-one-kas/Gittyup/suites/8090060580/artifacts/349266256

**Comment by alex-ball** [comment]
The permission confirmation was from running that command within Terminal; having accepted it once I'm not getting it again.

The experimental build still gives the "No terminal executable was found. Please configure a terminal in the configuration." message.

In the configuration, the Terminal tab defaults to name=ga, location=/usr/local/bin (Google Authenticator?). I have tried it with these values in place and also blank, and with name=Terminal, location=/System/Applications/Utilities/Terminal.app/Contents/MacOS, and with name=Terminal.app, location=/System/Applications/Utilities, with the same result each time.

**Comment by exactly-one-kas** [comment]
The Terminal tab was used for putting GitAhead into `$PATH` (hence `ga`), but this will be removed with the next full release.

You can set the terminal command in the Tools tab:
![image](https://user-images.githubusercontent.com/16035731/187956781-992237ff-8354-4ef7-bab0-b47ba72b7c59.png)

**Comment by alex-ball** [comment]
Ah, okay, that makes more sense. Thanks!

I've now tried setting Terminal emulator command=`open -b com.apple.Terminal .`; with this in place,

- in the experimental build , the "Open Terminal" button still results in the same popup message;
- in the production build v1.1.2, the "Open Terminal" button works as expected.

Looking at the UI, I think I would have expected to use `"%1"` (which doesn't work) instead of `.` in the above command, so there might need to be a bit more user help around this?

**Comment by anzvanie** [comment]
@exactly-one-kas @alex-ball Thanks for you solution, working for me on v1.1.2.

**Comment by alex-ball** [comment]
There is still an issue that the code to autodetect Terminal on MacOS isn't currently working, but I suppose that is a more specific bug.

**Comment by Murmele** [comment]
The problem here is that nobody has a mac and investigating using a virtual box was at least for me a mess. If you could provide as a solution that would be nice

**Comment by alex-ball** [comment]
I was a bit concerned I might have to learn C and the inner workings of the Mac, but happily this is not the case. I have just successfully compiled the app on macOS, and it seems all the clues are in this thread.

I have put the changes in PR #288.
