### ISSUE TITLE
Discarding changes in a repository will remove unstaged changes in submodule / reset submodule

### ISSUE THREAD

**Issue by DeeFuse** [Murmele/Gittyup#263]
I've noticed that Gittyup 1.1.2 will reset all unstaged changes in a submodule when you run 'Discard changes' in the parent repository.
The filename can be different, multiple files will be reset as well. It will even revert the commit of the submodule to the one you last had checked out in the main repository.

Steps to reproduce: 

- Clone my test reposiotry `git clone --recursive https://github.com/DeeFuse/Gittyup-Test`
- Change someting in `README.md`
- Change something in `Gittyup-Test-Module/README.md`
- Open repository in Gittyup
- Discard changes only in `README.md` 
-> `Gittyup-Test-Module/README.md` will be reset as well

![1](https://user-images.githubusercontent.com/7376678/188176753-8d0aebbb-012d-43f8-a6d7-57c0362577ed.PNG)
![2](https://user-images.githubusercontent.com/7376678/188176762-f6fc9a77-7bde-4efc-9631-133403f6e17f.PNG)
![3](https://user-images.githubusercontent.com/7376678/188176771-ad5f00e8-ad8d-4869-8621-e90af50d357c.PNG)

**Comment by Murmele** [comment]
I can confirm this and it is not because of the same name.

**Comment by Murmele** [comment]
The problem is that if no submodule is selected. In RepoView the submodules of the repo are used which is wrong
