### ISSUE TITLE
Amend feature mislabeled

### ISSUE THREAD

**Issue by lonix1** [Murmele/Gittyup#265]
i just used the amend feature, and to my horror it actually performed a (soft, I think) reset. Took a while to realise what happened. Luckily I didn't lose anything (I don't think so anyway, I hope!).

The amend should "amend" the previous commit, not reset it.

Related: https://github.com/Murmele/Gittyup/issues/94

**Comment by Murmele** [comment]
![grafik](https://user-images.githubusercontent.com/10099533/190986660-644d72ed-2490-4c40-ac13-63a4e249a893.png)

Yes it is implemented as soft reset

**Comment by Murmele** [comment]
![grafik](https://user-images.githubusercontent.com/10099533/190987126-9996dccd-cef9-45d9-93ea-979a7698b953.png)

**Comment by Murmele** [comment]
We can implement a dialog with author committer, message, ... listed there and the user can modify the values and then click on "amend" to apply the changes.
