### ISSUE TITLE
Is the External Diff feature removed from Gittyup when forking GitAhead?

### ISSUE THREAD

**Issue by SergeDorna-Philips** [Murmele/Gittyup#275]
I'm evaluating switching over from GitAhead to Gittyup but launching the external diff.

Previously in GitAhead you could right click on a change and select "External Diff" which would launch what was configured in the options under ``Tools / External diff``.

In Gittyup, You need to select a file, then right click in the diff to get the menu with the external diff option.

Can the same menu be added back to the file list?

**Comment by Murmele** [comment]
Hi @SergeDorna-Philips, 

currently it is not implemented for the listview. There is an ongoing merge request, but I was not able to finish it yet.
![grafik](https://user-images.githubusercontent.com/10099533/191194964-21d22937-9cc0-41e3-a5a3-d5c872211c2e.png)
