### ISSUE TITLE
Allow amending commit dates

### ISSUE THREAD

**Issue by exactly-one-kas** [Murmele/Gittyup#277]

**Comment by H-4ND-H** [comment]
Hello, tnx for all the great work, I want to contribute to the project, if no one is working on this issue, I guess its a good starting point.

**Comment by exactly-one-kas** [comment]
Hello, thank you for the nice words and the effort! I'd recommend starting on the `Amend` branch (currently at commit `df37b3d8e7fb32764d4499529996ddc04908df76`)
