### ISSUE TITLE
Deleting image preview looks strange

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#282]
![image](https://user-images.githubusercontent.com/10099533/192131106-77bbcb52-341e-4cb2-afbf-8264a0d94037.png)

https://github.com/Murmele/Gittyup/pull/146

maybe we can show instead of the new one a trash can?

**Comment by exactly-one-kas** [comment]
This doesn't happen for me on Windows for some reason
![image](https://user-images.githubusercontent.com/16035731/192502238-68a55157-7c2e-483d-98e2-7fac4873f630.png)

**Comment by Murmele** [comment]
looks fine with 1.2.2

![image](https://user-images.githubusercontent.com/10099533/214102182-43f37eb4-ecdd-4771-9aa3-5c9bd6809f96.png)
