### ISSUE TITLE
Crashes after wrong Gitlab / Github credentials

### ISSUE THREAD

**Issue by 0verEngineer** [Murmele/Gittyup#294]
If i try to add an Account in Gittyup for Gitlab or Github with non-working credentials a MessageBox "Host requires authentication" is shown. However after clicking the MessageBox away Gittyup crashes.

**Comment by 0verEngineer** [comment]
It does not happen on the current master branch, but on the latest Flatpak.

**Comment by exactly-one-kas** [comment]
This has been solved with #201 and will be included in the 1.2.0 release (see #272, coming soon™)
