### ISSUE TITLE
"New branch" dialog offers "stash" as starting point

### ISSUE THREAD

**Issue by exactly-one-kas** [Murmele/Gittyup#309]
![image](https://user-images.githubusercontent.com/16035731/195567615-edc90a60-e0a9-44be-8e82-4d16cfcea240.png)

@Murmele can we just remove the dropdown when "new branch" has been selected from the commit context menu?

**Comment by Murmele** [comment]
You mean showing just
- a label from the **commitlist context menu**
- and the combobox if selected from the **menu bar**?

**Comment by exactly-one-kas** [comment]
Exactly

**Comment by Murmele** [comment]
Oh this is really anoying, sorry I did not understand previously completely the issue. We have to fix it for v1.2.0

**Comment by Murmele** [comment]
I have a fix for it
