### ISSUE TITLE
Adding Gitlab Account anymore visible

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#316]
![grafik](https://user-images.githubusercontent.com/10099533/196109750-0ad7eaa0-45a7-4790-86f5-f5de800473ea.png)

In the left pane ith shows the wrong icon it should be gitlab

Probably it come with #313

**Comment by exactly-one-kas** [comment]
Ah, putting the `Gitea` item to the end of `Account::Kind` should do the tick I think.

**Comment by Murmele** [comment]
But then there is still something wrong? Maybe somewhere numbers are used instead of the enum and therefore it comes to this issue?

**Comment by exactly-one-kas** [comment]
I'm already fixing that - the account type is being saved and loaded using the enum's numerical value, I'll switch to strings

**Comment by Murmele** [comment]
> I'm already fixing that - the account type is being saved and loaded using the enum's numerical value, I'll switch to strings

But then we need also a compability check to prior 1.1.2
