### ISSUE TITLE
[UI Intent Clarification] Number of Account-Types Shown

### ISSUE THREAD

**Issue by OdinVex** [Murmele/Gittyup#318]
https://github.com/Murmele/Gittyup/blob/13c18f545d02a26cca9fc78012a0dc0212a6eafc/src/ui/TabWidget.cpp#L86

The line above specifically limits the number of 'account types' (kinds) that can be shown on the default Gittyup view, such as 'Add GitHub/Gitea/Bitbucket/Beanstalk...' Should there be a limit? Maybe increase it? GitLab is currently not shown (but only on this short list). If you attempt to add an account, you can easily select GitLab and other accounts, but perhaps this section of the UI may need to be revisited to make it easier to understand that other types aside the list exist. Maybe a scrollable list.

**Comment by exactly-one-kas** [comment]
The limit should be increased in tandem with adding new account types (since it's an enum) - we forgot to do that here

**Comment by Murmele** [comment]
Yes I thought there was something like this haha
