### ISSUE TITLE
It'd be nice to know the difference between the latest version of the original gitahead and this fork

### ISSUE THREAD

**Issue by KOLANICH** [Murmele/Gittyup#33]

**Comment by Murmele** [comment]
Check out [this](https://flathub.org/apps/details/com.github.Murmele.Gittyup)
Version 1.0.0 changes are the changes to the latest version of Gittyup.

**Comment by KOLANICH** [comment]
Flathub is a bad website. It is completely unworking without JS. I guess the changelog should be here in the first place.

I guess i'd be better to give this link: https://github.com/Murmele/Gittyup/commit/2218aac5c4fa495feb9c4f1e10499d10e9f771b3
