### ISSUE TITLE
Update download url

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#335]
Currently in Gittyup we are using the following download url: https://github.com/Murmele/gittyup/releases/download/stable/Gittyup%1%2.%3

The problem is that we don't have anymore a stable release.

As a hot fix I changed the label of the latest development release to be the "stable" it is the same as gittyup_v1.2.0 but this was a dirty fix.

We have to change it to:
https://github.com/Murmele/gittyup/releases/download/v%1/Gittyup%2%3.%4

**Comment by exactly-one-kas** [comment]
Changing the URL to `https://github.com/Murmele/Gittyup/releases/latest/download/Gittyup%1%2.%3` should suffice
![image](https://user-images.githubusercontent.com/16035731/198654292-10716290-f688-42ed-a817-0a794b1f20ee.png)

**Comment by Murmele** [comment]
ok perfect then we can do this ^^. Neverthless we have to be carefull for the next release to create again a stable tag.

**Comment by alerque** [comment]
> we have to be carefull for the next release to create again a stable tag

No, you shouldn't need that.

At most you need it to bail yourself out of the previous release updating to current because the old URLs were not a good scheme, but if you fix the URL as @exactly-one-kas shows above you will not need a "stable" tag the next time around.

**Comment by exactly-one-kas** [comment]
We'll have to do it one last time, since the old URL is still present in 1.2.0
