### ISSUE TITLE
SSH permissions

### ISSUE THREAD

**Issue by RichardFevrier** [Murmele/Gittyup#339]
Using the Flatpak version of Gittyup, I am unable to push on a remote.
If I am using the command line `git push remote branch` I have no problem.
So I guess Gityup is unable to access to my SSH key agent or something related.

**Comment by Murmele** [comment]
What SSH key agent are you using? I am using ssh for github and gitlab. I have my private key in /home/$USER/.ssh where do you have it?

**Comment by RichardFevrier** [comment]
I am using OpenSSH, my keys are in the same place as you, except that `/home` is a symlink to `/var/home` in my case.
I have checked in **Flatseal** and **Gittyup** has `socket=ssh-auth` enabled.
When I try to push with **Gittyup** a `ssh-agent` process is spawned `/usr/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh`

**Comment by RichardFevrier** [comment]
I finally found a solution [here](https://major.io/2022/08/05/use-gnome-keyring-with-sway/) for my **Fedora Silverblue**
By adding the `ssh` component for the `gnome-keyring-daemon.service`
Except that I had to not to `export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh` otherwise it would not work

**Comment by major** [comment]
Happy to help!
