### ISSUE TITLE
[Feature request] Coloured items in unstaged/staged file lists

### ISSUE THREAD

**Issue by lonix1** [Murmele/Gittyup#341]
Files in the staged / unstaged lists have labels "M", "D", "?", etc., and they are all in blue:
<img src=https://raw.githubusercontent.com/Murmele/Gittyup/master/rsrc/screenshots/double_treeview_single_line_staging.png />

Please consider changing the colours for those icons?

For example, here's a random screenshot I found showing how it's done in gitkraken:
<img src=https://www.codingwithcalvin.net/wp-content/uploads/2022/02/unstaged-files-1024x555.png />

See how the icons are red, green, orange to denote deleted, added, modified.

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/199187846-3ef815f5-be5f-43af-9652-c0600bafe25c.png)

Not colorizing only M, A, D but also both:M, ...

**Comment by Rob-bb** [comment]
Hi, sorry to raise the dead, but I have a question about these icons.  I am unable to find any documentation on them, but I think I can guess M = modified, A = added, D = deleted.  What does "?" icon mean, is it untracked?  and if a directory has M, ?, and D icons is that just an indicator of the status of its contents?

**Comment by Murmele** [comment]
Yes for the directory it is related to the content inside :)
