### ISSUE TITLE
Adding Items to .gitignore on first launch/fresh repository crashes GittyUp

### ISSUE THREAD

**Issue by ArkyonVeil** [Murmele/Gittyup#353]
So I started a fresh project, created a repository and while making the first commit I decided to add a few items to .gitignore so the repository remains clean. All 3 tries crashed Gittyup. 

After making a single commit, and adding to .gitignore after that, it no longer crashed.

Occurred on 1.20

**Comment by Murmele** [comment]
How did you ignore? Context menu from the treeview on the right?

Might be the same problem as in #349 .

**Comment by ArkyonVeil** [comment]
Yep, right clicked the unstaged file and pressed ignore.

**Comment by Murmele** [comment]
Ok. Patch is already ready :)

**Comment by Murmele** [comment]
This is now in the latest development version
