### ISSUE TITLE
Update to v1.2.0 failed on Windows for unable to close some windows

### ISSUE THREAD

**Issue by gsardiscot4u** [Murmele/Gittyup#355]
I had my repo open.
The windows with suggested update appeared and I clicked on "Install Update".
The download started (very slowly the download) and after the 100% clicked on "Install and Restart" (at this moment I have the main window with my repository and the "Update Gittup window").
The window "Update failed" appears and after "Ok", nothing happen.

Can I send some telemetry or log? How?
I am on Windows 11.
Some screenshots below.

![Check_Update_Gittup](https://user-images.githubusercontent.com/115140522/200789480-3b22e46d-8110-44c2-89f6-2d5195c47615.jpg)
![Install_and_restart_Gittup](https://user-images.githubusercontent.com/115140522/200789498-55db4721-289a-4005-8aeb-4997021ec3ac.jpg)
![Update_failed_Gittup](https://user-images.githubusercontent.com/115140522/200789515-e5dccae7-11f5-4143-aa80-efdedccf4b4d.jpg)

**Comment by exactly-one-kas** [comment]
This is fixed in version 1.2.0, you'll have to manually download and install Gittyup one last time: https://github.com/Murmele/Gittyup/releases/download/gittyup_v1.2.0/Gittyup-win64-1.2.0.exe
