### ISSUE TITLE
Can't revert deleted changes

### ISSUE THREAD

**Issue by lonix1** [Murmele/Gittyup#362]
Repro:
- create file, stage, commit
- edit file: remove all contents
- go to gittyup, click file: all contents are red because they were removed
- click "x" ("Discard hunk")
- gittyup crashes

What is expected: when "discarding deleted changes", those changes should be "added" back to the file. (Sort of like a reset, for that hunk.)

**Comment by Murmele** [comment]
Hi @lonix1 which version are you using and which os?

Can you run Gittyup in console and provide the log output?

**Comment by Murmele** [comment]
Just execute `flatpak run com.github.Murmele.Gittyup`

**Comment by Murmele** [comment]
Hi @lonix1 can you share the complete log not only the ASSERT? The problem is from there we are not able to find out in which line of our code it happens

**Comment by Murmele** [comment]
able to reproduce with 
Gittyup v1.2.0 - Sonntag, 30. Oktober 2022 - 1bc0ffc
