### ISSUE TITLE
Overflow in information displayed when cloning large repositories

### ISSUE THREAD

**Issue by mhmzx** [Murmele/Gittyup#373]
Although this is not a big problem, when the cloned repositories is too large, the current progress displayed in real time in the log will overflow, like this:

```
[-] 10:59 - Clone - https://github.com/JetBrains/intellij-community.git
     remote: Enumerating objects: 7876335, done.
     remote: Counting objects: 100% (12111/12111), done.
     remote: Compressing objects: 100% (4794/4794), done.
     Receiving objects: 48% (3855387/7876335), -2113079880 bytes | 941.75 KiB/s.
```

**Comment by mhmzx** [comment]
Sorry, it seems like that it is a bug of git, I close this issue.

**Comment by exactly-one-kas** [comment]
No, you've been right - this is a problem with Gittyup: We're currently building that message ouself (it's just meant to resemble the standard GIT's messages)
