### ISSUE TITLE
Logging into files

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#376]
Currently on windows it is not possible to see the debug logs. The idea is to replace qDebug() and storing the debug data into files instead of output to stdout.
Adding an option to the Debug menu wether the data should be logged into a file or shown on the stdout

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/203153139-dcfc8c44-9395-45d4-b2ad-633dd53fcdd0.png)

**Comment by exactly-one-kas** [comment]
I'd advise to leave `qDebug()` in and use ` qInstallMessageHandler()` to write the messages into the file

**Comment by rokejulianlockhart** [comment]
https://github.com/Murmele/Gittyup/issues/376#issuecomment-1322609824

> ![image](https://user-images.githubusercontent.com/10099533/203153139-dcfc8c44-9395-45d4-b2ad-633dd53fcdd0.png)

https://translate.google.com/?text=y+Fenster+Extras+Hilfe+Debuggen%0AAbst%C3%BCrzen%0AIndexer-Fortschritt+loggen%0ACredential-Helper+loggen%0ARemote-Verbindung+loggen%0AAlle+Diffs+laden%0ACommits+durchgehen&tl=en&langpair=auto|en&tbb=1

<blockquote>

y Tools Help window Debug
Crash
Log indexer progress
Log credential helper
Log remote connection
Load all diffs
go through commits

</blockquote>

**Comment by Murmele** [comment]
Implemented with https://github.com/Murmele/Gittyup/pull/556
