### ISSUE TITLE
Git Repo settings are not saved on Flatpack kubuntu

### ISSUE THREAD

**Issue by kulica** [Murmele/Gittyup#378]
On every program run there are no git repos anymore.

**Comment by 0verEngineer** [comment]
@kulica What do you mean exactly - Git repos or Git repo settings?

I can confirm that the RepositorySettings Dialog has problems, on the General tab the checkboxes are not saved, only if you change the username the checkboxes are also saved.

This has nothing to do with flatpak, this happens everywhere.

**Comment by Murmele** [comment]
@0verEngineer for me on windows even I change a checkbox and then changing the name and closing the window, the config is not stored, only the name, but not in <Repository>/.git/gittyup/config. Did not find yet where

**Comment by Murmele** [comment]
problem is that there exist two config files
- .git/gittyup/config
- .git/config

**Comment by Murmele** [comment]
![grafik](https://user-images.githubusercontent.com/10099533/214360574-790d2c72-96f8-4fed-8e22-5bdaec1acb5e.png)

**Comment by Murmele** [comment]
![grafik](https://user-images.githubusercontent.com/10099533/214361025-1408de30-1900-43af-a5bd-7af085a74267.png)

**Comment by Murmele** [comment]
@kulica can you try the version from this build:
https://github.com/Murmele/Gittyup/pull/441
