### ISSUE TITLE
Focus on files

### ISSUE THREAD

**Issue by arialdomartini** [Murmele/Gittyup#382]
Any movement from the commit list (e.g. cursor down or up) would change focus to the list of changed files.
This makes browsing the history via the keyboard very inconvenient.

Is there the way not to loose the focus from the current panel?

**Comment by exactly-one-kas** [comment]
There's currently no way to disable this behavior, it'll have to be fixed

**Comment by Murmele** [comment]
@arialdomartini can you test in version 1.2.1 and above if it is working now?

**Comment by arialdomartini** [comment]
I can confirm that in 9f7574a25ff6318be9004a489c0e8bf9ae6c3f08 (1.2.1) it works perfectly!
Cool!

**Comment by Murmele** [comment]
Great!
