### ISSUE TITLE
How to enable Translation

### ISSUE THREAD

**Issue by ShuiHuo** [Murmele/Gittyup#394]
I through [AUR](https://aur.archlinux.org/packages/gittyup) and Flatpak installation Gittyup, after opening can only see English, can't see the Chinese translation, I need to do?（我通过 [AUR](https://aur.archlinux.org/packages/gittyup) 和 Flatpak 安装 Gittyup，打开后都只能看到英文，看不到中文翻译，我需要做些什么？）

**Comment by exactly-one-kas** [comment]
This is a bug in either Gittyup itself or the AUR's PKGBUILD

The problem here seems to be that the translations don't get installed correctly
This will probably get fixed with #191

**Comment by exactly-one-kas** [comment]
In the meantime, you can try using the following PKGBUILD: https://gist.github.com/exactly-one-kas/0382ea74b2729437439ee0d0495b65ae

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/207121345-59183a9e-277f-48de-9af4-bb37d19298bf.png)

![image](https://user-images.githubusercontent.com/10099533/207121379-90df5d6f-6986-428f-a525-e2f6948250e6.png)
