### ISSUE TITLE
Amend previous commit with new changes

### ISSUE THREAD

**Issue by csetera** [Murmele/Gittyup#395]
Is it possible to amend a previous commit with new staged changes?  I see that the ability to amend a previous commits properties was recently added, but I'm not seeing a way to take a new set of changes and amend the previous commit to include those changes.  Is that possible and I'm missing how?

**Comment by exactly-one-kas** [comment]
You should be able to simply stage the changes you want to be included in the amended commit and then execute the amend

Does this work for you?

**Comment by csetera** [comment]
Apologies.  I had been looking for "Amend" near the "Commit" button.  I didn't originally find it in the Repository menu.  Seems to work as expected.  Thanks!
