### ISSUE TITLE
Flatpak can't access all filesystem

### ISSUE THREAD

**Issue by jucajuca** [Murmele/Gittyup#396]
Hello,

I was using gitahead as my git client, it worked quite good so I tried switching to Gittyup. Unfortunately the installation with Flatpaks in Ubuntu is not working as expected. It can not access drives mounted under /media because it does not have the proper rights. I looked for a quick solution but apparently this is an underlying issue with flatpaks.

Are you considering releasing Gittyup as a .deb package or even better through an ubuntu repository?

**Comment by Murmele** [comment]
Hi,
this is a limitation of the flatpak package for security reasons. You can overwrite the permissions easily using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal). Just give it the permission to access your drive

**Comment by jucajuca** [comment]
Unfortunately I already tried Flatseal and it did not help. I have mounted an encrypted hard drive where all the code is saved.  I tried with an older version of gitahead and it worked, but gittyup could not access it. This is the error

`    [-] Unable to checkout 'my-branch' - failed remove - '/run/flatpak/doc/b10d5cbc/my-repo/.my-file.yml' is locked: Permission denied`

**Comment by luboA** [comment]
Is it possible to make distribution through standard repositories and install it by apt? I think that snap and flatpak are just hell for users and limit them.

**Comment by Murmele** [comment]
The problem is the effort on the developer side to maintain all of those packages then. For Arch Linux we have a maintainer which is working with us to get the package running. But there is nobody for debian, ubuntu, ...

**Comment by jucajuca** [comment]
After further investigation, the problem was related to the mount options of the hard drive. If someone is willing to support the packaging that would also facilitate the updates. Thanks!

**Comment by OdinVex** [comment]
As noted above, Flatseal is perfectly capable of exposing the filesystem to a Flatpak app. If it isn't working as intended, it is due to the way it is mounted. As far as supporting anything non-Flatpak/ninja install, you're probably on your own. I'm no fan of Flatpak, so I run simple git checks for releases as a cron-job that then notifies me of updates for git-only softwares. A few simple bash scripts to grab the latest, compile, install, no need for a PPA in my case. Of course, Manjaro/Arch make it so much better with the AUR instead.

**Comment by SBCV** [comment]
Thx @OdinVex

So what most people probably need is:
Install Flatseal: `flatpak install flathub com.github.tchx84.Flatseal`
Run Flatseal: `flatpak run com.github.tchx84.Flatseal`
Under the entry `gittyup` check `All system files`

![gittyup_flatseal](https://github.com/Murmele/Gittyup/assets/19491335/646530b1-39e2-4bbb-b1d6-4cd1f2529da2)
