### ISSUE TITLE
default template for commit message

### ISSUE THREAD

**Issue by farfromrefug** [Murmele/Gittyup#403]
Would be very cool to be able to define a default template for commit message to replace the "Update..."
For people like me using conventional commits i would love it to be "chore: Update...."

**Comment by Murmele** [comment]
Commit templates are already available. Only the fefault part has to be implemented.
@farfromrefug do you know the commit message template editor?

**Comment by farfromrefug** [comment]
@Murmele yes I have seen it and am already using it. Indeed the only addition is to use a template as default commit message

**Comment by Murmele** [comment]
Ok great. It seems to be a trivial feature, so maybe it will be implemented by somebody soon

**Comment by Murmele** [comment]
@farfromrefug can you try #413. This is a first draft, What do you think?

**Comment by farfromrefug** [comment]
@Murmele awesome. Yes I could try. Never tried to build gittyup but that should be simple. I ll try and report

**Comment by Murmele** [comment]
@farfromrefug you don't have to build. Just check the ci artifacts insode the mr. There we have flatpak, windows and macos

**Comment by Murmele** [comment]
Here: https://github.com/Murmele/Gittyup/actions/runs/3807676116

**Comment by farfromrefug** [comment]
@Murmele awesome thank you!

**Comment by farfromrefug** [comment]
@Murmele tried to install the flatpak from the PR action but got an error:
```
The application com.github.Murmele.Gittyup depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub' [Y/n]: n
error: The application com.github.Murmele.Gittyup/x86_64/development requires the runtime org.kde.Platform/x86_64/5.15-21.08 which was not found
Time: 0h:00m:14s      
```
though i already have gittyup install through flatpak. Any idea? thanks

**Comment by Murmele** [comment]
hmm yes this is strange can you try to install it?
`flatpak install org.kde.Platform/x86_64/5.15-21.08`

**Comment by Murmele** [comment]
Uninstall the other version before: ``flatpak remove com.github.Murmele.Gittyup` otherwise you have to Gittyups installed

**Comment by farfromrefug** [comment]
@Murmele thanks it worked.
So i tried the build.
* I see that if i select a template it is reused when i close / open the last template is used. So it is stored per repo or globally?
* which raises the question, can we have global commit templates?
* maybe it is not possible but if my template is `chore: %|` would it be  possible when i stage files for the commit message to become `chore: Update filename` ? Like it does when there is no template. That way for most common tasks i dont have to enter any message while still using conventional commits.

Great so far!

**Comment by Murmele** [comment]
Hi @farfromrefug 

I have to check but I thought the templates are globally.

To get the original behaviour you have to use `Update ${files:3}` `%|` defines just the location of the cursor after applying the template

**Example:**
````
Description: %|

files: ${files:3}
````

This is a template which adds a description header and all staged files to the commit message. Additionally the cursor will be placed directly after the `Description: ` word. So you can directly start to type. Does it work for you?

**Comment by farfromrefug** [comment]
@Murmele i will test but it seems perfect!

**Comment by KaKi87** [comment]
Hi,
I'm sorry but I looked for this feature and I can't figure out how to use it, could someone please explain ?
Thanks

**Comment by Murmele** [comment]
Hi @KaKi87 ,

Just create a new commit template. The first one is used as default and automatically applied

**Comment by KaKi87** [comment]
Thanks but how to do that exactly ?

**Comment by Murmele** [comment]
It is the small button next to the commit message: https://murmele.github.io/Gittyup/
