### ISSUE TITLE
DoubleTreeView / TreeView doesn't save after reopen application or change repository

### ISSUE THREAD

**Issue by VladimirKunyavsky** [Murmele/Gittyup#407]
When opening a commit with changes in large files, a memory leak occurs when the Double Tree View is displayed. When Tree View is enabled no leakage occurs. But when the program is restarted, the Double Tree View is enabled again. Therefore, the Tree View is not saved after restarting the program or changing the repository.
![Screenshot_20221222_225918](https://user-images.githubusercontent.com/121262077/209225391-04463844-e9b3-4488-a109-906ae2ce33c2.jpg)

**Comment by Murmele** [comment]
Wheter a memory leak you mean a loose of state?

**Comment by VladimirKunyavsky** [comment]
When the program tries to show changes (big changes) in large files, the amount of RAM used increases many times and crashes when the RAM is full (I have 8 GB).
But this doesn't happen if change preview is off (Double Tree View is off and Tree View is on).
I understand that this is a matter of my system resources, but if the View was saved, then there would be no problems when opening the program.

Kubuntu 22.10 x64, 8GB DDR3, Intel Core i5.

**Comment by Murmele** [comment]
@VladimirKunyavsky it might be something similar to this one: #303?

**Comment by VladimirKunyavsky** [comment]
Somewhat similar, but I have files not only of the XML format, but when reading changes in files of other formats, crashes occur.
But as Dekomorii described, a function to skip reading large files (preferably with an indication of the size) would be very useful.
Thank you!

**Comment by Murmele** [comment]
@VladimirKunyavsky  thanks for the clarification, so I close this one in favour of the other.

If it is xml or something else is not relevant
