### ISSUE TITLE
Changes not shown correct

### ISSUE THREAD

**Issue by 0verEngineer** [Murmele/Gittyup#409]
![Screenshot from 2022-12-23 14-33-40](https://user-images.githubusercontent.com/105462605/209409056-a95b894e-4fea-4d1d-835e-293ad78413c1.png)

Today i had the problem that Gittyup was showing wrong modifications on a file. In my screenshot you can see the diff view of VScode and Gittyup, the VScode one is correct.
However i could not reproduce it a second time as it went away after restarting from terminal for logging.

**Comment by Murmele** [comment]
Hi @0verEngineer, which version did you use?

**Comment by 0verEngineer** [comment]
Sorry, forgot the Version info, Flatpak 1.2.0

**Comment by Murmele** [comment]
Is this somehow reproducable?

**Comment by 0verEngineer** [comment]
Did not happen a second time for me sadly

**Comment by Murmele** [comment]
Then lets close it for now, If you encounter it again, just open this one.
