### ISSUE TITLE
(Gittyup v1.2.2) External diff tool does not launch on Ubuntu 22.10

### ISSUE THREAD

**Issue by DonutWrecker** [Murmele/Gittyup#438]
I'm using a third-party software for diff and merge operations (meld). I don't know what's the issue, since I was able to launch the diff tool via other git gui clients. This is probably not a meld issue, since kdiff3 does not launch as well.
Here is my .gitconfig settings related to the diff/merge tools:
[merge]
	tool = meld
[mergetool "meld"]
	cmd = meld "$LOCAL" "$MERGED" "$REMOTE"
[diff]
	tool = meld
[difftool "meld"]
	cmd = meld "$LOCAL" "$REMOTE"

**Comment by Murmele** [comment]
Hi @DonutWrecker are you using the flatpak version? Can you open the application from the command line `flatpak run com.github.Murmele.Gittyup`, and checking if you see any error there?

**Comment by Murmele** [comment]
Is the diff tool highlighted here: 
![grafik](https://user-images.githubusercontent.com/10099533/214284362-604dba1a-bc5e-4705-88bb-75e88a46b80a.png)

Did you use a previous version of Gittyup where it worked?

**Comment by DonutWrecker** [comment]
> Hi @DonutWrecker are you using the flatpak version? Can you open the application from the command line `flatpak run com.github.Murmele.Gittyup`, and checking if you see any error there?

Hey @Murmele, thanks for the quick reply. I'm using the flatpak version, yes. When I run the command you've provided I get an error:
![error](https://user-images.githubusercontent.com/67188697/214379204-06bfa766-0f78-44fc-b4f8-b6442db2f3ba.png)

Here is how my "Tools" windows looks on Ubuntu 22.10:
![gittyup_ubuntu1](https://user-images.githubusercontent.com/67188697/214379459-64f5685f-a866-4e1d-b6ac-9857b59fcf9a.png)
![gittyup_ubuntu2](https://user-images.githubusercontent.com/67188697/214379487-b0b3252b-ab4a-487d-a50b-23d678134d1b.png)

I've also installed Gittyup on my Windows machine, and the difftool works there perfectly:
<img width="327" alt="meld_win2" src="https://user-images.githubusercontent.com/67188697/214379839-91edf78a-c54a-4c47-8d1e-af1a90fc7339.png">
<img width="700" alt="meld_win" src="https://user-images.githubusercontent.com/67188697/214379867-0a215212-8890-4ef9-a619-44f9a5286770.png">

And here how .gitconfig looks on my Windows 10 machine:
<img width="361" alt="meld_gitconfig_win" src="https://user-images.githubusercontent.com/67188697/214379986-a03568c0-c396-444c-b4af-abfbd2e38e09.png">

I've only tried Gittyup a month ago on Windows, though I don't recall trying the difftool.

**Comment by Murmele** [comment]
@DonutWrecker can you try the Build artifacts from #444 I got it work there

**Comment by DonutWrecker** [comment]
> @DonutWrecker can you try the Build artifacts from #444 I got it work there

Yes, that works perfectly. Though I got an SSL error on launch, and I have clicked on "ignore" without thinking. And I can't seem to reproduce the error I got now. So I can't really tell if anything else is wrong.

Thanks for the quick action.
