### ISSUE TITLE
[Feature Request] Disable automatic updating on Flatpak version

### ISSUE THREAD

**Issue by AluminiumTech** [Murmele/Gittyup#442]
In GittyUp installed using Flatpak, GittyUp prompts users to download new updates if it's not up to date but it tries to download and install new updates as if it's not using Flatpak. Needless to say this does not do anything because of the nature of using Flatpaks. (The way to update GittyUp as a Flatpak once installed is via command line or via a GUI application such as the Pop!_Shop on Pop!_OS or Ubuntu Software Centre on Ubuntu)

The prompts that a new version is available is alright and worth keeping on the Flatpak version but I think the automatic downloading and installing of updates should be disabled for the Flatpak version.

The check for update button in the Help Menu should also probably be disabled on the Flatpak version. I don't know if it would be too much effort to also add a possible tool tip for hovering over that disabled menu button with something like "You must update GittyUp from the terminal or from the application where you installed GittyUp."

Thanks

**Comment by Murmele** [comment]
Hi @AluminiumTech,

There is a possibility to disable checking for updates. In the Check for updates we are informing the user to not install manually if the package is downloaded from flathub.
![image](https://user-images.githubusercontent.com/10099533/214507384-729a481a-6d50-4d7c-9613-dee97a03f2ab.png)

![image](https://user-images.githubusercontent.com/10099533/214507275-9ea6f1a6-6a7a-4fa1-a270-d9697343ea0b.png)

One possibility we can do is disabling the update for the flathub version but not for the flatpak version we provide in the release second. This can be done by having by default the update disabled with a cmake flag and in our CI we are enabling it.

I will check it out I think this should be quick

**Comment by Murmele** [comment]
https://github.com/Murmele/Gittyup/pull/443
