### ISSUE TITLE
TreeView test no longer pass on Arch Linux

### ISSUE THREAD

**Issue by FabioLolix** [Murmele/Gittyup#467]
Hello, with v1.2.0 all test passed; but since v1.2.1 TreeView fail, haven't hunted the responsible commit yet

```
QDEBUG : TestTreeView::fileMergeCrash() Name:  "Unstaged"  Row:  0 :  "security_configs" ; Count:  0
QDEBUG : TestTreeView::fileMergeCrash() Name:  "Unstaged" , countCollapsed(): 0
QDEBUG : TestTreeView::fileMergeCrash() Name:  "Unstaged" Current Collapsed:  0 ; New Collapsed:  -1
TreeView: /usr/src/debug/gittyup-git/Gittyup/src/ui/TreeView.cpp:169: void TreeView::setCollapseCount(int): Assertion `value >= 0' failed.
```

Building the package using the AUR pkgbuild gittyup-git, attached there is the check log of makepkg

[gittyup-git-1.2.1.r0.gf364ff0-1-x86_64-check.log](https://github.com/Murmele/Gittyup/files/10777894/gittyup-git-1.2.1.r0.gf364ff0-1-x86_64-check.log)

**Comment by alerque** [comment]
Have you tried the stable build of v1.2.2 using the [gittyup](https://aur.archlinux.org/packages/gittyup) That builds for me including passing tests. Even if you want to proceed to building Git HEAD from there it would be interesting to compare and know if that builds for you (note I build and test in a clean chroot so if you do it on your host system that might indicate something else you have around that has changed and affects this).

**Comment by FabioLolix** [comment]
> (note I build and test in a clean chroot so if you do it on your host system that might indicate something else you have around that has changed and affects this).

I build in clean chroot for my local repo and sometimes with makepkg to see if packages build for most people, for me it fails the same in both conditions

> Have you tried the stable build of v1.2.2 using the [gittyup](https://aur.archlinux.org/packages/gittyup) That builds for me including passing tests.

No, I see some flags are different but at the moment I don't have the broadband and I'm tethering from the phone so I'll delay build like this

**Comment by Murmele** [comment]
Hi @FabioLolix ,

can you have a look into this MR: https://github.com/Murmele/Gittyup/pull/397 There is also a PKGBUILD I used for testing. I tried to clean up the structure of Gittyup as much as possible

**Comment by FabioLolix** [comment]
For sure Murmele when I will have internet again; the broadband's operator router that should have arrived yesterday instead will arrive in 5 days maybe, the situation is ludicrous here.

**Comment by Murmele** [comment]
@FabioLolix please check out the new pkgbuild in #397
