### ISSUE TITLE
"Edit in External Editor" not working

### ISSUE THREAD

**Issue by systemoperator** [Murmele/Gittyup#482]
Selecting a commit, right-clicking on a file in the list of committed files and choosing `Edit in External Editor` does not work. (But `Show in Default File Browser`, `Open this version` and `Save Selected Version as...` are working.)

Observation: Nothing happens at all (no error, no window).

Operating system: Debian 11, Mate Desktop 1.24.1 with Marco window manager
Running the latest version of Gittyup (v1.2.2), using flatpak

Contrarily, with the latest version of **GitAhead**, the `Edit in External Editor` command works flawlessly (e.g. with the text editor `pluma`). The `pluma` window pops up. Maybe there is a problem with associating external executables?

**Comment by Murmele** [comment]
This problem is solved in the latest version, it is not officially released yet, but you can download the bundle from: 
https://github.com/Murmele/Gittyup/releases/tag/development
![image](https://user-images.githubusercontent.com/10099533/222816023-466771ec-2409-41d1-bcb9-c91a14b65075.png)

**Comment by systemoperator** [comment]
@Murmele Great, it works. :)

**Comment by Murmele** [comment]
Perfect :)
