### ISSUE TITLE
OpenSSL build error on macOS: [test/v3ext.c] Include the header <string.h>

### ISSUE THREAD

**Issue by LostInCompilation** [Murmele/Gittyup#486]
Building OpenSSL on macOS 13 fails with the following error:
```
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
```

This issue is known by OpenSSL and has been fixed. But because Gittyup still uses OpenSSL 1.1.1, building Gittyup/OpenSSL is broken.
This is the OpenSSL issue: https://github.com/openssl/openssl/issues/18720

Maybe consider upgrading OpenSSL (and Qt) or make a custom branch of it.

EDIT: Maybe related #451

**Comment by Murmele** [comment]
@LostInCompilation can you try #516 ?

**Comment by LostInCompilation** [comment]
Yes, was able to build successfully using #516.

**Comment by Murmele** [comment]
I will merge it after the release next days
