### ISSUE TITLE
Option to add author to compact history view

### ISSUE THREAD

**Issue by mahomedh** [Murmele/Gittyup#487]
Firstly, thanks for carrying on the development of GitAhead, and as an open source project.

Would it be possible to have an option to show the Author/Committer in the Compact Mode view next to the date?

Currently you have to disable Compact View, or click on the entry to view the author. Compact view is much easier to read, especially on wide screen. I appreciate not everyone needs this column in compact view, so hence asking to make it optional.

**Comment by Murmele** [comment]
Hi @mahomedh , thanks for the kind words! Can you explain more about what you mean with compact mode?

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/224544911-94d6d84f-188a-4c0c-84f1-b248134e3da8.png)

**Comment by mahomedh** [comment]
Hi @Murmele 

This is what I mean by the detail history/ commit log view. As you can see, it shows Author and date on the first line, then the ID and then the commit message.

![image](https://user-images.githubusercontent.com/8697001/224743456-2c411c63-eb0d-47e7-8343-15c371a2b519.png)


But below is what you see when you choose "compact" mode. As you can see, the commit message, date and ID are on one line. So my request is for the ability to have an option to show the author on this same line.

 
![image](https://user-images.githubusercontent.com/8697001/224743928-863a6be3-86ac-4bfb-8a7e-8588e4f04f77.png)

**Comment by Nico-Duduf** [comment]
Hi!
Thanks also for your work on Gitahead/Gittyup, that's a great tool (and I've tested many, many git UIs....)

Regarding this commitlist, I think it deserves a few options indeed.
I can understand why some may need to have the author in compact mode; this could come with another option to hide the commit id (and that'd make room for the author on small screens in compact mode)
Most of the time I really don't care about the commit id and it makes it difficult to read other data.

I know Qt and I could create a pull request, when I'll have a bit of time to write it.

From what I've seen I would:

Add the two settings and their id in Settings
Add the option in the CommitToolBar
Modify the CommitDelegate  in commitlist.cpp

That's seems right?

Is there anything specific to know to compile and test?

**Comment by Nico-Duduf** [comment]
I had time to do that already, it's #552

**Comment by jensenr30** [comment]
@Murmele 
Can this issue be closed?  I think this feature has been implemented and is working on `master`.

**Comment by Murmele** [comment]
Thanks for the reminder :)
