### ISSUE TITLE
Committing opens another file with unstaged changes to view

### ISSUE THREAD

**Issue by lightr4in** [Murmele/Gittyup#493]
Having a repository with multiple tracked files that have unstaged changes, 
you would want to go through the code and commit the lines of a file individually.

But when I commit, it just opens the topmost file from the `Unstaged Files` list.

The following gif should illustrate it well.

![gittyup-commit-bug](https://user-images.githubusercontent.com/120530289/225129379-0a9ce141-5459-4907-a6e8-386f8af5d643.gif)

I've tested it with the latest 1.2.2 (flatpak) dev version from February 26 (`e7eccf6`) on a manjaro machine with gnome.

**Comment by Murmele** [comment]
@lightr4in can you test with 1.3.0 again? I potetially fixed it an this mr:

https://github.com/Murmele/Gittyup/pull/306

**Comment by lightr4in** [comment]
@Murmele The problem seems to be fixed now and the UI feels smoother, thank you!
