### ISSUE TITLE
[feedback] gittyup on homebrew not available

### ISSUE THREAD

**Issue by theCollectiv** [Murmele/Gittyup#498]
While trying to install gittyup via homebrew, there was no formulae 'gittyup' available.
 
```
 >> brew install gittyup
Running `brew update --auto-update`...
Warning: No available formula with the name "gittyup". Did you mean gitup?
==> Searching for similarly named formulae...
==> Formulae
gitup

To install gitup, run:
  brew install gitup
```

Maybe the [Murmele/Gittyup: Understand your Git history!#how-to-install](https://github.com/Murmele/Gittyup#how-to-install) section should be updated.

**Comment by theCollectiv** [comment]
```
 >> brew install --cask gittyup
Error: Invalid `--cask` usage: Casks do not work on Linux
```

I'm using linux/ubuntu.

PS.: I'd prefer homebrew over flatpack (which the install-instructions also suggest), so I tried it first.

**Comment by Murmele** [comment]
Hi, yes homebrew is only for Macos.
For linux: https://flathub.org/apps/details/com.github.Murmele.Gittyup

**Comment by theCollectiv** [comment]
> Hi, yes homebrew is only for Macos. For linux: https://flathub.org/apps/details/com.github.Murmele.Gittyup

Homebrew works on Linux quite well ...[Homebrew on Linux — Homebrew Documentation](https://docs.brew.sh/Homebrew-on-Linux).

Normally, I'm not a fan of flatpak, because even small programs (< 50 mb) become huge as a flatpak (>500 mb). Nevertheless, to sneak into gittyup, I installed via flatpak.

And gittyup is pretty awesome, thx for your work :-)

**Comment by Murmele** [comment]
> Normally, I'm not a fan of flatpak, because even small programs (< 50 mb) become huge as a flatpak (>500 mb). Nevertheless, to sneak into gittyup, I installed via flatpak.

This is true because of the required platform. But if multiple apps are using the same platform then the memory usage is getting smaller per app

**Comment by Murmele** [comment]
> And gittyup is pretty awesome, thx for your work :-)

Thank you :) I am happy to hear it :)

I did not know that brew works also on linux
