### ISSUE TITLE
"Filter by path" is broken

### ISSUE THREAD

**Issue by exactly-one-kas** [Murmele/Gittyup#50]
Inputting queries yield wildly varying results when they shouldn't

![clipboard](https://user-images.githubusercontent.com/16035731/144074927-b3ba1518-e79d-4b94-9a74-4ece8814cf58.png)
![clipboard](https://user-images.githubusercontent.com/16035731/144075027-c848bb4f-976f-4ca6-a1d9-11980b5069a4.png)
![image](https://user-images.githubusercontent.com/16035731/144071208-549fa713-8382-4ee6-a561-cc4614f75779.png)

**Comment by Murmele** [comment]
@exactly-one-kas can you add the commit id where it worked and where not?

**Comment by Murmele** [comment]
index::write gets never called, maybe because the indexer fails for some reason?
