### ISSUE TITLE
[Feature request] [UX] Automatically refresh on focus

### ISSUE THREAD

**Issue by KaKi87** [Murmele/Gittyup#505]
Hello,

It would be nice of Gittyup to automatically refresh status when the window is put in foreground after being in background.

Use case :
1. The user opens Gittyup, it is in foreground, status is updated ;
2. The user opens an editor and edits a file, Gittyup is in background, status is outdated ;
3. The user goes back to Gittyup, it is in foreground, status would be updated.

Thanks

**Comment by Murmele** [comment]
Seems to be a bug, because Gittyup automatically refreshes whenever a file was modified

**Comment by KaKi87** [comment]
After further testing, it turns out that yes, Gittyup does refresh files, but not the git status, not like when pressing the refresh button.

**Comment by Murmele** [comment]
> 

Yes this is true, this data is written in the .git folder and currently we don't track this folder.

**Comment by Murmele** [comment]
duplicate of #216

**Comment by redactedscribe** [comment]
I'd also like to see the git status refresh automatically. If you stage something in VS Code, you must first press Refresh in Gittyup to update the status.
