### ISSUE TITLE
Donations don't seem to work

### ISSUE THREAD

**Issue by MarcelInTO** [Murmele/Gittyup#532]
I got the latest release and saw the donate button. When I attempted to donate on liberpay, it gave me a notice saying that it couldn't because you were not set up to receive funds.

**Comment by Murmele** [comment]
Hi @MarcelInTO thanks for the hint, I will check

**Comment by Murmele** [comment]
@MarcelInTO does it work now?

**Comment by MarcelInTO** [comment]
Yes it does!

**Comment by Murmele** [comment]
@MarcelInTO Thank you very much!
