### ISSUE TITLE
Access to a private server

### ISSUE THREAD

**Issue by spoo0k** [Murmele/Gittyup#539]
When adding account for a private gitlab server, cannot access it and asks auth data again.

**Comment by exactly-one-kas** [comment]
For GitLab, you need to [create an access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) and use it as the password
Additionally, make sure that the URL you entered ends with `/api/v4`

Does it work with that?

**Comment by spoo0k** [comment]
It's works! thank you.
