### ISSUE TITLE
Change color of diffs (for colorblind)

### ISSUE THREAD

**Issue by MikeKholomeev** [Murmele/Gittyup#540]
As a partially colorblind person, I'd like to set up colors for diffs as I like. 

Is there a possibility for this right now?

**Comment by Murmele** [comment]
I think creating your own theme might help. Tools->Window -> Add new theme in the drop down menu.

Is there a specific name of your colorblind? Maybe we can then add your theme to our defaults so it might help also others

**Comment by MikeKholomeev** [comment]
> Tools->Window -> Add new theme in the drop down menu.
Wow! Thanks! it helped.

>Is there a specific name of your colorblind? Maybe we can then add your theme to our defaults so it might help also others
Naah, I don't think that my colorblindness is typical... Never used any of the preset colorblind options in the games - they looked awful to me.

**Comment by Murmele** [comment]
Great that it was so easy :)
