### ISSUE TITLE
L'alphabet cyrillique ne s'affiche pas

### ISSUE THREAD

**Issue by jhon65496** [Murmele/Gittyup#554]
L'alphabet cyrillique ne s'affiche pas

Exemple de projet contenant des commentaires en russe(cyrillique): https://github.com/Hihiz/WPF-MVVM-CRUD

![17 05 2023_08-10-08](https://github.com/Murmele/Gittyup/assets/128128859/e213ba81-cb8f-44ac-9998-15f0029ca961)

**Comment by Murmele** [comment]
duplicate #525.
Please check out the solution there
