### ISSUE TITLE
Import Configurations and Repositories from GitAhead

### ISSUE THREAD

**Issue by dumim** [Murmele/Gittyup#558]
Hi, I am migrating from GitAhead to Gittyup. I cannot find any information on how to do this migration so that I don't have to reclone/repoint my repositories. I have 100s of private repos cloned through a Bitbucket connection on GitAhead. Any help would be appreciated. Thanks

**Comment by Murmele** [comment]
Hi @dumim. I think this should be possible, because it is just a configuration file.

Which operating system are you using?

**Comment by Murmele** [comment]
Linux: /home/<USER>/.var/app/com.github.Murmele.Gittyup/config/gittyup.github.com/Gittyup.conf

Just search for a Gitahead.conf on your system and rename it to Gittyup.conf and copy it into the correct folder

**Comment by dumim** [comment]
Hi @Murmele cheers for the reply! Using both Ubuntu and Mac
Thanks this should do the trick!

**Comment by dumim** [comment]
@Murmele hi reopenning since the GitAhead config file cannot be found:
These are the only files under `~/GitAhead/GitAhead/`
![image](https://github.com/Murmele/Gittyup/assets/30994223/01e02f0c-223d-4fe8-a4da-d9862b403c25)

**Comment by Murmele** [comment]
You will not find it in the install dir. Can you search in the .config file in your home directory?

**Comment by dumim** [comment]
Found it there, works like a charm! Thank you

**Comment by Murmele** [comment]
Great to hear!
