### ISSUE TITLE
Gittyup is always asking for passphrase even though I never set one

### ISSUE THREAD

**Issue by catalin560** [Murmele/Gittyup#561]
![Screenshot from 2023-05-22 19-01-37](https://github.com/Murmele/Gittyup/assets/22744333/478c0849-eb1f-46cb-8151-c00e3e65e14d)

This happens when you do any action like open repo, clone repo etc... And you can't even input blank passphrase...

**Comment by Murmele** [comment]
Hi  @catalin560 which version are you using and on which system?

**Comment by catalin560** [comment]
> Hi @catalin560 which version are you using and on which system?

I'm on Linux Mint, using the flatpak version 1.3

**Comment by Murmele** [comment]
Which credential store are you using?
Tools -> Options
![grafik](https://github.com/Murmele/Gittyup/assets/10099533/9850fccc-717a-4b0a-a17f-69161f3c54a8)

**Comment by Zefling** [comment]
Same problem : KDE / 1.3.0

![image](https://github.com/Murmele/Gittyup/assets/3032555/4db3175d-16bb-4167-a449-7d5be47952f7)

**Comment by Berinkton** [comment]
I had the same problem.
I think i fixed it by setting the fallback ssh key path under Tools -> Options -> Misc
to the path where my ssh key is located.
I don't know why the ssh passpharse dialog appears if this is not set.

![image](https://github.com/Murmele/Gittyup/assets/13868663/b7aa0f3b-deeb-492b-bafb-2275378d736c)

**Comment by catalin560** [comment]
[GCM](https://github.com/git-ecosystem/git-credential-manager) fixed it for me, I haven't had any problems with it.
![Screenshot_20231215_103540](https://github.com/Murmele/Gittyup/assets/22744333/e3ee1df4-bf4c-4d4a-af07-8f8097e131f2)
