### ISSUE TITLE
Allow hiding untracked files in "Unstaged Files" list

### ISSUE THREAD

**Issue by pablovacatello** [Murmele/Gittyup#587]
It'd be nice to have the option to hide untracked files from the "Unstaged Files" list. I tried setting status.showuntrackedfiles = no in the repository config, but that doesn't hide the untracked files from the gui (it does hide them when running git status on the command line).

**Comment by pablovacatello** [comment]
For further reference, I found a discussion about a similar request for Gitahead that was left open: https://github.com/gitahead/gitahead/issues/224

**Comment by Murmele** [comment]
Good idea! Can you try to get the pr working for Gittyup?

Adding a checkbox somewhere around here so you can easily check and uncheck
![grafik](https://github.com/Murmele/Gittyup/assets/10099533/ea682c6a-d261-4789-8f25-ed173f9eff8d)

- So we have to check if we just wanna just hide them in the treewidget (Adding changes to DiffTreeModel) or
- Creating the diff with ignored untracked files.

Which version do you prefer?

**Comment by pablovacatello** [comment]
I was thinking the best place to add the option would be to the cogwheel menu to the left of "Staged files", since it already handles display settings for those files.

Creating the diff with ignored untracked files would bring the benefit of less disk access when the repo has many untracked files, I think? I would be fine with either solution though.

I just use the binary version of Gittyup, but I might try to compile from source this weekend and if I manage to set that up I might take a stab at a PR.

**Comment by pablovacatello** [comment]
Here, I created a PR for this feature:
https://github.com/Murmele/Gittyup/pull/591

![hideuntrackedfiles](https://github.com/Murmele/Gittyup/assets/31071712/558d4ec0-a66a-4ef9-9230-fa3cf75bdaf1)

**Comment by pablovacatello** [comment]
#591 was merged so I'm closing the issue!
