### ISSUE TITLE
Gittyup gets confused with work-tree out of git-dir

### ISSUE THREAD

**Issue by ysalmon** [Murmele/Gittyup#612]
Gittyup records repos by their worktree in the Recent list, which relies on the assumption that the git-dir and the work-tree are in the same path. This is not always the case.

```
cd /tmp
mkdir a b
git --git-dir a --work-tree b init
touch b/test
```

Opening ``/tmp/a`` in Gittyup does display the adequate work-tree, with ``test`` as an untracked file.

However, this gets recorded as ``b``, not ``a``, in the Recent list. Moreover, opening the repo from that entry in the Recent list gives an error "/tmp/b does not contain a valid git repository", which is true, but irrelevant.

**Comment by Murmele** [comment]
Hi, did you have a look into git submodules? I think this is better than having nested git repositories

**Comment by ysalmon** [comment]
Yes I do, but in this case they are not practical. Anyway, the problem is really about the work-tree not being a subfolder of the git repo. I will update the initial post to give a better MWE.

**Comment by Murmele** [comment]
Thanks for the MR.
If you have
- a
   - repository A
- b
  - repository B
  - subfolder
       - workdir repoA
       
Do you ignore the subfolder `subfolder` then, otherwise you have to stage in both repositories?

**Comment by ysalmon** [comment]
I stage in both repositories, and not always the same files. Those are latex files, so we need them to be in the same place in order for my colleagues to configure their texmf without too much trouble, but I publish only those that I authored personally.
--
Cordialement,

Yann Salmon

Depuis mon téléphone ; excusez la brièveté.

**Comment by Murmele** [comment]
Ah ok I understand thanks for the clarification. I will check out your MR
