### ISSUE TITLE
Build fail release 1.3.0

### ISSUE THREAD

**Issue by Pro-pra** [Murmele/Gittyup#626]
Hi all, google not help me there GIT_BUF_INIT_CONST provided :(
```
/src/git/Branch.cpp:86:17: error: 'GIT_BUF_INIT_CONST' was not declared in this scope; did you mean 'GIT_BUF_INIT'?
   86 |   git_buf buf = GIT_BUF_INIT_CONST(nullptr, 0);
      |                 ^~~~~~~~~~~~~~~~~~
      |                 GIT_BUF_INIT
```

**Comment by Murmele** [comment]
Hi,
which version of libgit2 are you using?
Did you execute `git submodule update --init --recursive`?

**Comment by Pro-pra** [comment]
yes, i launch git submodule update --init --recursive

I use system libgit2-1.7.1 and bundled libgit2 with option USE_SYSTEM_LIBGIT2=OFF

**Comment by Pro-pra** [comment]
USE_SYSTEM_LIBGIT2=OFF is help me, thank you!
