### ISSUE TITLE
Not found lua modules

### ISSUE THREAD

**Issue by Pro-pra** [Murmele/Gittyup#631]
After local build and install i see in log:
```
$ gittyup
PANIC: unprotected error in call to Lua API (cannot open /builddir/build/BUILD/gittyup-6bf49f007a9fb0577910885607833373d0552101/conf/System.lua: No such file or directory)
```
file System.lua i found in /usr/share/Gittyup/themes/System.lua
option -DLUA_MODULES_PATH may be help me?

**Comment by Murmele** [comment]
the problem is that somehow the System.lua file is not found. Can you build with debug messages enabled so that you get more debug output?

**Comment by Pro-pra** [comment]
thank you, i fixed issue. 
May be help option:
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_DATADIR=share/%{name} \
	-DBUILD_SHARED_LIBS=OFF \
	-DDEBUG_OUTPUT=OFF \
and drop option:
-DLUA_MODULES_PATH=%{_datadir}/lua \
