### ISSUE TITLE
[Feature Request] Gitea Support

### ISSUE THREAD

**Issue by arcoast** [Murmele/Gittyup#64]
Just discovered Gitahead today and disregarded it due to development no longer being carried out and then found gittyup awesome!

Wondered if there's any prospect of supporting [Gitea](https://gitea.io/en-us/)?  Regardless on the feasibility of this, thanks for this fork and for working on it.

**Comment by Murmele** [comment]
Hi @arcoast , what do you expect with Gitea support?
In Gittyup you are able to clone from every host you want with File->Clone Repository

**Comment by alexporth** [comment]
Not to OP but Gitea has a similar structure to Github. So being able to log in to the service and getting all repos associated with the account as remotes, like what happens with Github, would be nice.

**Comment by MMariusch** [comment]
That would definitely help. I tried to add my account by manually setting the URL but it doesn't work. Alternatively a tutorial would be nice.

**Comment by OdinVex** [comment]
I use Gitea, so I'm looking at the code to determine what will need to be added or extended. I've already implemented the entire UI relating to Gitea's authentication, the only thing left is the backend communication (learning how Gitea can be interfaced).

**Comment by OdinVex** [comment]
Fixed by Pull Request #313.
