### ISSUE TITLE
UI error (Build version)

### ISSUE THREAD

**Issue by ajoaespinola** [Murmele/Gittyup#642]
Trying to build Gittyup in my Linux Mint setup. Well, this is the result...

![image](https://github.com/Murmele/Gittyup/assets/6198654/71c0bf18-fbc6-4208-880d-c10dd662fb4e)

OS: Linux Mint 21.2 (Base: Ubuntu 22.04 LTS)
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu

Steps followed:
```
git clone https://github.com/Murmele/Gittyup.git

cd Gittyup

git submodule init
git submodule update

# Start from root of gittyup repo. (Gittyup folder)
cd dep/openssl/openssl

./config -fPIC
make

# Start from root of gittyup repo. (Gittyup folder)
mkdir -p build/release
cd build/release
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../..

ninja
```

Any hint? Thanks in advance.

**Comment by Murmele** [comment]
I had this problem also sometimes. But I just ignored it and now it is gone. Can you try with Qt6 (https://github.com/Murmele/Gittyup/pull/429) ?

**Comment by ajoaespinola** [comment]
Thanks for the comments @Murmele. I didn't want to install Qt6 just to "trying" this, so i try something else and it works!. In the Qt5 Configuration Tool I just ignore the compile gittyup version and it works just fine.

**Comment by ajoaespinola** [comment]
Sorry, I closed it by mistake

**Comment by Murmele** [comment]
Thanks for the feedback, I don't think we can do anything here, but at least there is a workaround.
