### ISSUE TITLE
[Feature Request] Option to deemphasize or hide commit author in commit list

### ISSUE THREAD

**Issue by raniesantos** [Murmele/Gittyup#651]
- **Version:** 1.3.0
- Installed from Flathub

**Current behavior:**
Author name is in bold text and emphasized over the commit message.

**Request:**
I would like an option to unbold the author name and bold the commit message instead.
Alternatively, just add an option to hide the commit author.

**Reason:**
The commit author isn't useful information when working on solo/personal projects.
Even in team projects, I believe that the commit message is much more important information than the author.

**Comment by Murmele** [comment]
Similar implementation like here: https://github.com/Murmele/Gittyup/pull/552
