### ISSUE TITLE
Templates doesn't insert filenames

### ISSUE THREAD

**Issue by redactedscribe** [Murmele/Gittyup#658]
Templates is unintuitive, probably because it's broken.

Selecting one from the list doesn't update the commit message to include the currently staged files: Clicking a "Chore" template with `chore: %| ${files:2}` as its template value will insert "chore:  " (no filenames).

v1.3.0

**Comment by Murmele** [comment]
![image](https://github.com/Murmele/Gittyup/assets/10099533/f7ebe1e5-de77-418c-977c-ba109dd840e7)

For me it works fine. Did you stage? It uses as files the filenames of the staged section

**Comment by redactedscribe** [comment]
Create 2 templates:

tmpl1: `chore: %| ${files:1}`
tmpl2: `chore: %| ${files:2}`

Then stage 3 files. Commit message is `chore:  .gitignore, and 2 more files`.

Select tmpl2. Commit message is now `chore:  `.

It seems to be broken and unpredictable.

**Comment by Murmele** [comment]
What do you mean 

> But what's inserted is tmpl1's template even though tmpl2 was selected last.

Did you move tmpl1 as first in the list?

**Comment by redactedscribe** [comment]
No. I guess that's not how it works then (my expectation was that it would use the last one which I picked). At that point I would have to repick tmpl2, but as noted, currently only `chore:  ` is inserted.

**Comment by Murmele** [comment]
Ah now I understand, you choose it manually not automatically. I was able to reproduce

**Comment by Murmele** [comment]
![image](https://github.com/Murmele/Gittyup/assets/10099533/5fa6a467-6af9-4992-a6e1-f7ff2d1606ee)

No files are passed when doing it manually. I have to check

**Comment by Murmele** [comment]
This will fix your issue:

https://github.com/Murmele/Gittyup/pull/667

**Comment by redactedscribe** [comment]
Thank you.
