### ISSUE TITLE
Double tree does not show diff anymore

### ISSUE THREAD

**Issue by thehrlein** [Murmele/Gittyup#685]
I was using gittyup for a while without any issue, but since 2 days I am missing the diff window. I am using Double Tree View and only see stages files and unstaged files, but I don't see any change that was made in the files

How can I bring back the window to see the changes in the file?

**Comment by Murmele** [comment]
Hi,
can you show how it looks now?

**Comment by thehrlein** [comment]
<img width="1520" alt="Bildschirmfoto 2024-01-18 um 15 01 31" src="https://github.com/Murmele/Gittyup/assets/7392270/392d2307-f89b-4176-b604-5d1f8cd57c4a">

**Comment by Murmele** [comment]
I think it is just hidden. Which version are you using? Can you update to the latest stable release? There something is implemented so that this cannot happen.

Which OS are you using?
If this did not help, you have to delete the config file then it should appear again

**Comment by thehrlein** [comment]
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Version: v1.3.0 - 2023-04-20

Where do I find the config?

**Comment by Murmele** [comment]
Can you install once the development version? I have to check if the fix is only in the dev version or also in the stable.

**Comment by thehrlein** [comment]
Installed the development version (flatpak) and with this I see the diff window again :)

**Comment by Murmele** [comment]
Great. :) then the fix was introduced after 1.3.0 😄
