### ISSUE TITLE
Gittyup Broken On Arch Linux After Recent Updates

### ISSUE THREAD

**Issue by Hamza-b93** [Murmele/Gittyup#691]
Gittyup is refusing to start on Arch Linux after the recent updates. Attempting to start Gittyup from the console results in the following error:

`gittyup: error while loading shared libraries: libcmark.so.0.30.3: cannot open shared object file: No such file or directory`

**Comment by alerque** [comment]
You have compiled `gittyup` yourself, then swapped out libraries behind it's back. You need to rebuild `gittyup` again so the configure & build process picks up the **current** system library versions and locations. This is true for all software that you build and install yourself. Apps installed via system packages are rebuilt whenever their dependencies are updated, when you do the building the you also need to rebuild them on system changes.
