### ISSUE TITLE
Opening GitAhead Project Repository

### ISSUE THREAD

**Issue by ProgrammingHobby** [Murmele/Gittyup#698]
Hello,
I tried to open a project created with GitAhead 2.6.3 with the current version of Gittyup. I got an error message that this is not a valid Git repository. Is there a way to open existing projects with Gittyup, or can/must I recreate the projects with Gittyup?

**Comment by Murmele** [comment]
Hi,

It should not matter which tool you are using. Are you still able to open the repository with GitAhead?

Which OS are you using?
Can you check the path you wanna open if there is a .git folder (it might be hidden)

If you have a terminal. Navigate into the folder and `git status` if you get the same error message then the repository is for some reason broken.

**Comment by ProgrammingHobby** [comment]
It is the repository in which I am currently working and also regularly make my commits, pushes and branches with GitAhead. OS is KUbuntu 22.04LTS 64bit in a Virtualbox VM. The project path is routed to the VM via shared folders. The hidden .git file is available.
I have not yet tested Git status in the console, but it should work since I am actively working with GitAhead in the repository.

**Comment by Murmele** [comment]
Thanks for the information.

Then it is probably this problem: https://github.com/Murmele/Gittyup/issues/396

Wether you can try the appimage package. The flatpak package allows only access to the home directory

**Comment by ProgrammingHobby** [comment]
Ok, that seems to correspond exactly to issue #396 for me.

I'll probably stick with GitAhead 2.6.3 for as long as I can and then see what happens.

Flatpak alone is already too much overhead for me, but then having to work with tricks to be able to use any flatpak application is not something I'm a fan of.

**Comment by Murmele** [comment]
In this case you can try out the appimage: https://github.com/Murmele/Gittyup/releases/tag/development

**Comment by ProgrammingHobby** [comment]
Gittyup Appimage works great. Appimage releases would be perfect for me.

**Comment by Murmele** [comment]
> Gittyup Appimage works great. Appimage releases would be perfect for me.

Great thanks for testing :)
