### ISSUE TITLE
Allow word wrap in `git diff` middle panel.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Murmele/Gittyup#706]
It's frustrating to view otherwise:

> ![20240227T190724GMT](https://github.com/Murmele/Gittyup/assets/42837531/02c6c3d6-0d94-42e4-ab09-723248008f29)

It would probably also be important for https://github.com/Murmele/Gittyup/issues/684#issue-2080855852.

**Comment by Murmele** [comment]
As workaround you can collapse the left panel by the button above and by pressing CTRL + M you hide wether the Commit List or the diff view (https://murmele.github.io/Gittyup/)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Murmele/Gittyup/issues/706#issuecomment-1971063944

@Murmele, thanks, but my lines are too long (I work on Markdown documents with only paragraph-delimiting line breaks, rather than Python-like mid-line line-breaks).
