### ISSUE TITLE
Uncommitted Changes doesn't disappear when it should

### ISSUE THREAD

**Issue by jensenr30** [Murmele/Gittyup#711]
When I open a repository that contains uncommitted changes, "Uncommitted Changes" is displayed regardless of the state of the checkbox.  Tested on v 1.3.0.  Feel free to assign to me.

[bug-uncommitted-changed.webm](https://github.com/Murmele/Gittyup/assets/3083835/b405e569-ed74-441c-9fb6-71b977b1e042)

**Comment by safetycar** [comment]
I thought that the checkbox was a way to be able to show the "uncommited changes" entry all the time even if there were no uncommited changes?
Now it behaves differently, hiding the entry when there are changes. I actually liked to always being able to go back go the "uncommited changes" position even it there was nothing new there.
