### ISSUE TITLE
CI Linux build broken

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#722]
https://github.com/actions/runner-images?tab=readme-ov-file

On 2024-03-17 ubuntu-latest changed from ubuntu-20.04 to ubuntu-22.04 which breaks our linux build (Validating appdata)

**Comment by Murmele** [comment]
Working:
```
(flatpak run:16892): dconf-CRITICAL **: 07:14:26.436: unable to create file '/run/user/1001/dconf/user': Permission denied.  dconf will not work properly.

(flatpak run:16892): dconf-CRITICAL **: 07:14:26.436: unable to create file '/run/user/1001/dconf/user': Permission denied.  dconf will not work properly.
./build/release/rsrc/linux/com.github.Murmele.Gittyup.appdata.xml: OK
```

Not working:
```
(flatpak run:16691): dconf-CRITICAL **: 17:50:04.587: unable to create file '/run/user/1001/dconf/user': Permission denied.  dconf will not work properly.

(flatpak run:16691): dconf-CRITICAL **: 17:50:04.587: unable to create file '/run/user/1001/dconf/user': Permission denied.  dconf will not work properly.

(process:2): GLib-GIO-ERROR **: 17:50:04.656: No GSettings schemas are installed on the system
Error: Process completed with exit code 133.
```

**Comment by Murmele** [comment]
https://installati.one/install-gsettings-ubuntu-schemas-ubuntu-22-04/

**Comment by Murmele** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1711

**Comment by Murmele** [comment]
Was fixed in flatpak

**Comment by RustoMCSpit** [comment]
im on linux mint LTS and the flatpak wont even open for me?

**Comment by Murmele** [comment]
> im on linux mint LTS and the flatpak wont even open for me?

Do you get an error message

**Comment by RustoMCSpit** [comment]
no it literally just doesnt open. i click on the icon and nothing happens

**Comment by RustoMCSpit** [comment]
i tried this in my terminal flatpak run com.github.Murmele.Gittyup


error: runtime/org.kde.Platform/x86_64/5.15-21.08 not installed

**Comment by Murmele** [comment]
> i tried this in my terminal: flatpak run com.github.Murmele.Gittyup
> 
> error: runtime/org.kde.Platform/x86_64/5.15-21.08 not installed

Thanks. Try: flatpak install org.kde.Platform/x86_64/5.15-21.08

**Comment by RustoMCSpit** [comment]
> > i tried this in my terminal: flatpak run com.github.Murmele.Gittyup
> > error: runtime/org.kde.Platform/x86_64/5.15-21.08 not installed
> 
> Thanks. Try: flatpak install org.kde.Platform/x86_64/5.15-21.08

is this a dependency that was accidentally forgoten in the flatpak?

**Comment by RustoMCSpit** [comment]
also if i install that will it install to every flatpak?

**Comment by Murmele** [comment]
This runtime is the base for the flatpak package. If you install the stable from flathub, they get installed. Probably when you install from the ci it might that they are not installed.

**Comment by RustoMCSpit** [comment]
> This runtime is the base for the flatpak package. If you install the stable from flathub, they get installed. Probably when you install from the ci it might that they are not installed.

i did install from flathub??

**Comment by RustoMCSpit** [comment]
can you try installing from your software mamager

**Comment by Murmele** [comment]
Thanks for the hint, I will try out

**Comment by RustoMCSpit** [comment]
> Thanks for the hint, I will try out

ok cool

**Comment by RustoMCSpit** [comment]
again im in linux mint lts cinnamon
