### ISSUE TITLE
Mouse wheel scrolling suddenly scrolls horizontally

### ISSUE THREAD

**Issue by awvalenti** [Murmele/Gittyup#779]
![Peek 07-06-2024 10-07](https://github.com/Murmele/Gittyup/assets/834921/77f77c35-0eb0-4bac-b64e-4ab55c183521)
When I'm scrolling using mouse, if pointer reaches horizontal scroll bar, it suddenly changes movement orientation. Please see GIF above.

I don't like this feature, especially when scrolling lots of pages. I think it should be changed to always vertical, or at least offer a config option to change this behavior.

**Comment by Murmele** [comment]
You can disable this by checking the wrap lines setting.
