### ISSUE TITLE
Thank you for your outstanding contribution. Do you have a timetable for downloading binary files? Gitahead often crashes and doesn't work.

### ISSUE THREAD

**Issue by rocex** [Murmele/Gittyup#78]

**Comment by Murmele** [comment]
Hi, on which system are you working?

**Comment by rocex** [comment]
Sorry, I didn't make it clear, My system is Windows 7 Sp1.

**Comment by Murmele** [comment]
@kas-luthor is using it currently in windows, but he is building it itself. So I think this is the only solution yet

**Comment by exactly-one-kas** [comment]
I'm currently in the process of wrapping up automatic builds from commits, so you should have a binary ready to download shortly.
