### ISSUE TITLE
Submit to WinGet.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Murmele/Gittyup#801]
**Request**

File a new package request for Gittyup at https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Help-Wanted%2CPackage-Request&projects=&template=package_request.yml&title=%5BPackage+Request%5D%3A+ for https://github.com/Murmele/Gittyup/releases/download/gittyup_v1.4.0/Gittyup-win64-1.4.0.exe. You can cite https://www.virustotal.com/gui/url/4be9ee273d6b0d66791d48e3c5411edd079ca549011fcc1e391d51062e8a8440.

I'll do so if nobody else does.

**Rationale**

It's Windows 10 and 11's default and official package manager.

**(Lack of) Duplicates**

https://github.com/Murmele/Gittyup/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+winget and https://github.com/microsoft/winget-pkgs/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+gittyup return 0 results.

**Comment by Murmele** [comment]
I don't have any problems with it. Thank you!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Murmele/Gittyup/issues/801#issuecomment-2371108352

@Murmele, submitted at https://github.com/microsoft/winget-pkgs/issues/174936#issue-2545260707. Thanks.
