### ISSUE TITLE
Git Lfs in flatpak package

### ISSUE THREAD

**Issue by Murmele** [Murmele/Gittyup#81]
At the moment git-lfs is not supported in the flatpak package. I tried to get it into the manifest, but it did not work yet:
https://github.com/flathub/com.github.Murmele.Gittyup/tree/work/git-lfs

**Comment by OdinVex** [comment]
Yeah, I can't use it to work with Unreal projects at the moment, I've stuck to using a plugin inside Unreal for now.

**Comment by Murmele** [comment]
If you are using a native version, it works fine. It is only related to the flatpak version

**Comment by Murmele** [comment]
Use the content of the described manifest
https://github.com/flatpak/flatpak-builder/issues/453

**Comment by OdinVex** [comment]
> If you are using a native version, it works fine. It is only related to the flatpak version

I was aware, it's one of the many reasons I really dislike AppImage/FlatPak/Snap stuff. Slowly migrating to Manjaro with AUR to end all of that kind of stuff, once and for all. Thank you for following up, though. :)

**Comment by Murmele** [comment]
Yes thats the drawback of it. But it is easier to maintain just one linux version 😄. I got now a hint so I might be able to fix it next days

**Comment by Murmele** [comment]
fixed in the new version of the flatpak. It might take one or two days until the version is published on flathub

**Comment by OdinVex** [comment]
> fixed in the new version of the flatpak. It might take one or two days until the version is published on flathub

Sad to say, I have the updated version (git-lfs is in the manifest and such), but something is wrong. It finds git-lfs, but opening up `Configure Repository` and checking `LFS` shows no URLs and a broken environment:

Inside LFS Environment:
`Error getting git version: exec: "git": executable file not found in $PATH`

**Comment by Murmele** [comment]
Thanks @OdinVex I will have a look into it

**Comment by OdinVex** [comment]
> Thanks @OdinVex I will have a look into it

I took more than a cursory glance at the Flatpak, and I've noticed I can't make a commit or unstage, nothing but git errors each time I try. `Error: failed to call git rev-parse --git-dir --show-toplevel: ""`

**Comment by Murmele** [comment]
I will have a look at the weekend why it is needed

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/161237682-8ad75c31-f3bd-4bfb-be66-fb92e3a88bd8.png)

**Comment by Murmele** [comment]
@OdinVex I merged your merge request. Thanks :)

**Comment by OdinVex** [comment]
@Murmele, Will check when Flatpak is updated. :)
