### ISSUE TITLE
Unable to unstage single files and commit

### ISSUE THREAD

**Issue by stingray21** [Murmele/Gittyup#91]
I am trying the new version and it works great with a test repo. Unfortunately I am having issues with staging and commiting for some of my production repos (which work with cli git and old gitahead).

I can stage by clicking on the checkbox next to the file, but not unstage single files. The only way to unstage is to click the "Unstage all" button. 

Commiting then results in an error
```
Unable to commit - failed to insert entry: invalid object specified - ScriptComponent 
```

It's a repo for a React project and it is fairly big. My system is Manjaro linux with Gnome and Wayland.

**Comment by stingray21** [comment]
Unfortunately I couldn't share the react project in which I noticed this behavior, but I know found a public repo which causes the same error for me.

https://github.com/WhatsApp/stickers

**Comment by exactly-one-kas** [comment]
Note: Current commit of that repository is https://github.com/WhatsApp/stickers/commit/0c51d2e48e71d3dd9e3475eb2095a6097c0f3950

**Comment by exactly-one-kas** [comment]
No, i just left the note for reproducability so I can look at the issue later on

**Comment by exactly-one-kas** [comment]
@stingray21 Is this issue still occurring with the current pre-release version? I can't reproduce this on my machine (64-Bit Arch Linux btw, Xorg, pre-release version)

**Comment by stingray21** [comment]
I don't think so, it's working for me as well 😃
