### ISSUE TITLE
Display full file content at a specific commit

### ISSUE THREAD

**Issue by Minabsapi** [Murmele/Gittyup#92]
From the GUI we can see file changes at a specific commit, but we can't view the whole file from it while `git show` allows that

An option to view the file content at a specific commit instead of current content, which is the current behavior, would be a nice addition. Perhaps by modifying the existing file viewing feature and changing Gittyup opened editor's behavior to view content read only (in that case why not replace the pen logo with an eye to convey the idea we're just looking)

**Comment by exactly-one-kas** [comment]
You can use the "single tree view" button to view the full tree and files of the selected commit. Does this satisfy your use case?

![image](https://user-images.githubusercontent.com/16035731/160567551-aee93688-c95b-4719-bd3c-4e5be8a09204.png)

**Comment by Minabsapi** [comment]
This is indeed a solution, but I was more thinking about bringing that to the double-tree view and replace the default behavior I explained earlier, as it in my opinion doesn't make much sense

**Comment by exactly-one-kas** [comment]
That's available in the double-tree view by using the `Blame` button
![image](https://user-images.githubusercontent.com/16035731/194512153-5a7f97dc-5aa0-483c-8c41-8b69196762aa.png)
It doesn't allow for a pop-out / pop-up window with the file content though (yet)

**Comment by exactly-one-kas** [comment]
We do have an option to open the file at the commit's version with the default program for the file
![image](https://user-images.githubusercontent.com/16035731/194512747-b9edc9f3-bc96-4eca-b0db-9da9868a6131.png)

**Comment by exactly-one-kas** [comment]
And opening in the built-in editor is possible as well
![image](https://user-images.githubusercontent.com/16035731/194513185-7525e4dd-f84d-4998-a107-a3f1ee8f0adb.png)

**Comment by exactly-one-kas** [comment]
@Minabsapi Does this work for you?

**Comment by Minabsapi** [comment]
This does the trick, especially the second option which is immediately more accessible (might be only me, but my first reflex for bringing additional file options was to right click not the file path header / separation element, but instead the file name in the committed file list). Thank you!
