### ISSUE TITLE
"Amend commit" advanced dialog

### ISSUE THREAD

**Issue by Minabsapi** [Murmele/Gittyup#94]
Amending a commit in Git enables a developer to modify commit message, but can do much more. It can also alter author date, creator...

An advanced dialog to change those attributes would be, I think, a nice addition. It would be just a matter of displaying the dialog on triggering the "Amend commit" option. That'd be also a welcome break from the current behavior of the GUI which seems to be just cancelling the commit, therefore incorrect since this is what "Reset" is intended for

**Comment by Murmele** [comment]
We can implement a dialog with author committer, message, ... listed there and the user can modify the values and then click on "amend" to apply the changes.
