### ISSUE TITLE
Crash: trying to add github account

### ISSUE THREAD

**Issue by luzpaz** [Murmele/Gittyup#98]
Reproduce:
* Start gittyup 
* Click the 'Add Github account'
* Enter username
* Enter personal access token or password
Result: 
![image](https://user-images.githubusercontent.com/4140247/152362810-14de3021-12e1-445b-a218-30c5216256c5.png)
* Click OK
Result: Crash  
`Segmentation fault (core dumped)`

Gittyup 1.0.0 (d52896fa79c5)
Compiled via the [AUR package gittyup-git](https://aur.archlinux.org/packages/gittyup-git/)

**Comment by jclaveau** [comment]
Same here from Flatpak
```shell
flatpak run com.github.Murmele.Gittyup --version
Gittyup 1.0.0
```

**Comment by Murmele** [comment]
![image](https://user-images.githubusercontent.com/10099533/164719967-8d864e59-ba4d-4530-98a2-990374cc5bda.png)
https://docs.github.com/en/rest/overview/other-authentication-methods

This is why it does not work anymore. But it should not crash

**Comment by Murmele** [comment]
For now the easiest way is to setup a ssh connection. I think we have to implement OAUTH2 to be able to use Github login in Gittyup
Adding ssh keys:
https://github.com/settings/keys

**Comment by exactly-one-kas** [comment]
Closing this since #201 has been merged
