### ISSUE TITLE
Cherry-pick overwrites author

### ISSUE THREAD

**Issue by machiav3lli** [Murmele/Gittyup#99]
GittyUp seems to overwrite the author of the commits when cherry-picked.

This is not the usual behaviour of git. It would be great to either have git's cherry-pick default behaviour or at least an option to disable the obverwritting.

And thanks for taking over GitAhead, I'm really liking the direction this project is taking.

**Comment by Murmele** [comment]
@machiav3lli can you have a look on the linked pullrequest if this is the behaviour you would like to see

**Comment by machiav3lli** [comment]
Seems theoretically right, I'll close it for now and test it later on and report. Thanks!
